{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-1.3.0-multiplatform-sources.jar",
          "url": "material3-1.3.0-multiplatform-sources.jar",
          "size": 526288,
          "sha512": "0e6b0c876de45bcb123703ab30c95906a700959886db6b60a0c13ee313fe0492df4427ef83f8afd33a5a126c7c5d6345c70024c97763624287a60cb68b181a2a",
          "sha256": "6f685e798874a0fefebe1664cb69346a517c1debed0982e372ba9f70114c4972",
          "sha1": "35212517f211d611530618732a615fb433b1c93b",
          "md5": "84c55d7184992fbace2b3a09d3d2e24e"
        },
        {
          "name": "material3-1.3.0-samples-sources.jar",
          "url": "material3-1.3.0-samples-sources.jar",
          "size": 58300,
          "sha512": "b70c1e94c6641a463bfa5bf9ed67e0972e4b8b44ef01e76c3a28880bf76996faa97157e9e64c4b2769d2f5ef5e7993c280dcacdd05b358573aed21b457a8a1e2",
          "sha256": "3329e1a97328bbeda1e9c4f8305037ef6c13ab227af31b8ea65f757c2e791162",
          "sha1": "785900bfcf93caf2c601e44d7194f12d13deddd7",
          "md5": "74345ebc9dc3ee902fc1b71b5afe36ea"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material3-1.3.0-versionMetadata.json",
          "size": 187552,
          "sha512": "9c44ce32a65c8f29b9be33af1e62d05658ff1c81ab3bb68e5f847043bf8cde4c0fe63b02d66f701d9ca8f406dfab922a63f0ef9fe076b2746d78997ca4aa818b",
          "sha256": "a645d6f918eb0aa1c88f72da5d8c56c87a86ba2e5e2caa8aa8c189fbdc2c658f",
          "sha1": "762adef54ca99ecbea896c08cba2b29b99a908ec",
          "md5": "164add2ead22b09dd5347d5d4ac3572e"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-metadata-1.3.0.jar",
          "url": "material3-1.3.0.jar",
          "size": 779,
          "sha512": "bb024903400e25f11e31b9d13575ae8870883aa974e193ff7f963be13ed55d095b38fa37be3e49a1458d699340bb6b41687b09d7573f85031ac0c209a482c88c",
          "sha256": "e2667048f898be236e8f3980d8137496bcafb626ebc4eedf32aa00f481f8fff7",
          "sha1": "441ff636812c1cad5bcfb3d084cc85d690d81144",
          "md5": "27a4d8fd017cf5c5b82a388b161e3539"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-kotlin-1.3.0-sources.jar",
          "url": "material3-1.3.0-sources.jar",
          "size": 452393,
          "sha512": "54862328f0c69ca943e031e805e190bf456dbb2dcb18b1c40ccf268458fec636b6c3947174be0a1b19cf0a5d3e4ef73d9189cc13bba8b0bd6fef20789a5d16e6",
          "sha256": "d77e02c6b3342ad573b4266e381d6dd34e7eab87ea6debad4d88240d1f175d6e",
          "sha1": "f51909d6af7ec68fc681549cf5f4e896af5319a3",
          "md5": "e005b326c0b7230cf392887e194a7697"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.3.0/material3-android-1.3.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.3.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.3.0/material3-android-1.3.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.3.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.3.0/material3-android-1.3.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.3.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.3.0/material3-desktop-1.3.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.3.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.3.0/material3-desktop-1.3.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.3.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.3.0/material3-desktop-1.3.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.3.0"
      }
    }
  ]
}