{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.1.1.jar",
          "url": "spring-boot-starter-4.1.1.jar",
          "size": 4767,
          "sha512": "87e10b55689e6c9489ea9ef21b4b0a3a564c68eaebb1b0b3b4a7c072d8d617628f6da73533365037217632900bcb2c7040c6ea93eb5c97cb8c2ad91a08b10df6",
          "sha256": "de5b2dd28400eda20914fd4a6054d0c201e68d2e4de35a25a4d89f054ccc2e63",
          "sha1": "50fe6a89fa4fd26e7caaec909ab1c4cc9afde5d4",
          "md5": "5d5008acc9638eca189bbcd581e164b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.1.1.jar",
          "url": "spring-boot-starter-4.1.1.jar",
          "size": 4767,
          "sha512": "87e10b55689e6c9489ea9ef21b4b0a3a564c68eaebb1b0b3b4a7c072d8d617628f6da73533365037217632900bcb2c7040c6ea93eb5c97cb8c2ad91a08b10df6",
          "sha256": "de5b2dd28400eda20914fd4a6054d0c201e68d2e4de35a25a4d89f054ccc2e63",
          "sha1": "50fe6a89fa4fd26e7caaec909ab1c4cc9afde5d4",
          "md5": "5d5008acc9638eca189bbcd581e164b3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.1.1-javadoc.jar",
          "url": "spring-boot-starter-4.1.1-javadoc.jar",
          "size": 4767,
          "sha512": "87e10b55689e6c9489ea9ef21b4b0a3a564c68eaebb1b0b3b4a7c072d8d617628f6da73533365037217632900bcb2c7040c6ea93eb5c97cb8c2ad91a08b10df6",
          "sha256": "de5b2dd28400eda20914fd4a6054d0c201e68d2e4de35a25a4d89f054ccc2e63",
          "sha1": "50fe6a89fa4fd26e7caaec909ab1c4cc9afde5d4",
          "md5": "5d5008acc9638eca189bbcd581e164b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.1.1-sources.jar",
          "url": "spring-boot-starter-4.1.1-sources.jar",
          "size": 4767,
          "sha512": "87e10b55689e6c9489ea9ef21b4b0a3a564c68eaebb1b0b3b4a7c072d8d617628f6da73533365037217632900bcb2c7040c6ea93eb5c97cb8c2ad91a08b10df6",
          "sha256": "de5b2dd28400eda20914fd4a6054d0c201e68d2e4de35a25a4d89f054ccc2e63",
          "sha1": "50fe6a89fa4fd26e7caaec909ab1c4cc9afde5d4",
          "md5": "5d5008acc9638eca189bbcd581e164b3"
        }
      ]
    }
  ]
}
