{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigationevent-compose/1.0.0/navigationevent-compose-1.0.0.module",
    "group": "androidx.navigationevent",
    "module": "navigationevent-compose",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14389689"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-compose.aar",
          "url": "navigationevent-compose-android-1.0.0.aar",
          "size": 29998,
          "sha512": "b7bc2d049cdde9324e2b295b4cb28227b15fdaa499f446bb3d743e54be9608e04d42b29723e982dfcd8ec30dd2df168a19025bbdfc93b483760b6e1ed6e6819f",
          "sha256": "5cee018dbe130b538d2c43cc6f383a109a98f19ba9c8d7a6dda8ca90a2034671",
          "sha1": "b6c1a5f3174a1d9fdbf8b8244e817ca25d5c773c",
          "md5": "567b6b2ee4f1e6c965a82976d8714f77"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "LocalView"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-compose.aar",
          "url": "navigationevent-compose-android-1.0.0.aar",
          "size": 29998,
          "sha512": "b7bc2d049cdde9324e2b295b4cb28227b15fdaa499f446bb3d743e54be9608e04d42b29723e982dfcd8ec30dd2df168a19025bbdfc93b483760b6e1ed6e6819f",
          "sha256": "5cee018dbe130b538d2c43cc6f383a109a98f19ba9c8d7a6dda8ca90a2034671",
          "sha1": "b6c1a5f3174a1d9fdbf8b8244e817ca25d5c773c",
          "md5": "567b6b2ee4f1e6c965a82976d8714f77"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent-compose is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-compose-android-1.0.0-sources.jar",
          "url": "navigationevent-compose-android-1.0.0-sources.jar",
          "size": 14442,
          "sha512": "b62a4ff76539dc148d006b80a2e9cbc2b9213f43c05dde45ada7a0220bdfe1098ee590e50b71296caa8831ff5b518b4ee2773fdd9ff12e9c4772179ae67afad3",
          "sha256": "0781754e368262504f08e63eabcf580e58cb73f6126c9484f64da6a1e0d1cfcf",
          "sha1": "5eff2094c55701ba62b3579758162e521965fc9f",
          "md5": "ff39595fb6de2841518668dc8f9156a9"
        },
        {
          "name": "navigationevent-compose-1.0.0-samples-sources.jar",
          "url": "navigationevent-compose-android-1.0.0-samples-sources.jar",
          "size": 5859,
          "sha512": "ade557bee51aab3e41cde6381162fb98e8053ab0a9349fad48367d34bd5cebab5a76cb5081ad0f933e4a3f27ffb56f4ada3f1c5b2563acde1cad98d44d2fc1ac",
          "sha256": "df63ae9684f469f4538795438481b802b394d365566b5af25487e0eef2f4ac6f",
          "sha1": "b7d83bf2bf811c87eec0c4133cf342e08043060e",
          "md5": "3dc3a37e0a809197bcd92e7bf8e9c888"
        }
      ]
    }
  ]
}