{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-reactor-netty",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor-netty",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.1.1.jar",
          "url": "spring-boot-starter-reactor-netty-4.1.1.jar",
          "size": 4742,
          "sha512": "a4fc22815be28c29cfd7ebb7b26212c439a0b9fb321cc12df2baf78674de7096837b044e7d5de19587d6812af264d503ac341dfb3f912fbe481c316d93da1884",
          "sha256": "8a6b77c051ac930ad3d0b2d4788e38c944bd649803c5b02db023874c0b58f4e5",
          "sha1": "6c1aa927d59c7762571b0ca03aafd71527e1adbd",
          "md5": "574ba380a10bbc2271b54c69f8a5fd40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor-netty",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.1.1.jar",
          "url": "spring-boot-starter-reactor-netty-4.1.1.jar",
          "size": 4742,
          "sha512": "a4fc22815be28c29cfd7ebb7b26212c439a0b9fb321cc12df2baf78674de7096837b044e7d5de19587d6812af264d503ac341dfb3f912fbe481c316d93da1884",
          "sha256": "8a6b77c051ac930ad3d0b2d4788e38c944bd649803c5b02db023874c0b58f4e5",
          "sha1": "6c1aa927d59c7762571b0ca03aafd71527e1adbd",
          "md5": "574ba380a10bbc2271b54c69f8a5fd40"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.1.1-javadoc.jar",
          "url": "spring-boot-starter-reactor-netty-4.1.1-javadoc.jar",
          "size": 4742,
          "sha512": "a4fc22815be28c29cfd7ebb7b26212c439a0b9fb321cc12df2baf78674de7096837b044e7d5de19587d6812af264d503ac341dfb3f912fbe481c316d93da1884",
          "sha256": "8a6b77c051ac930ad3d0b2d4788e38c944bd649803c5b02db023874c0b58f4e5",
          "sha1": "6c1aa927d59c7762571b0ca03aafd71527e1adbd",
          "md5": "574ba380a10bbc2271b54c69f8a5fd40"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.1.1-sources.jar",
          "url": "spring-boot-starter-reactor-netty-4.1.1-sources.jar",
          "size": 4742,
          "sha512": "a4fc22815be28c29cfd7ebb7b26212c439a0b9fb321cc12df2baf78674de7096837b044e7d5de19587d6812af264d503ac341dfb3f912fbe481c316d93da1884",
          "sha256": "8a6b77c051ac930ad3d0b2d4788e38c944bd649803c5b02db023874c0b58f4e5",
          "sha1": "6c1aa927d59c7762571b0ca03aafd71527e1adbd",
          "md5": "574ba380a10bbc2271b54c69f8a5fd40"
        }
      ]
    }
  ]
}
