{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jackson",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jackson",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.1.1.jar",
          "url": "spring-boot-starter-jackson-4.1.1.jar",
          "size": 4740,
          "sha512": "81eecc02a6af7089dead17d6998e4cfe0b8084267de9607bdcb9c70514adf2f5bfd390d23d624bfd90f65f1a10ca5a7584529137fb86274eee634ea497ea0aab",
          "sha256": "d30e594a3e0f3a090438fc22000a87ab577a3b80c674180a10544ca331207f24",
          "sha1": "f8cd6a81994a207a808564515e5104548d1967bb",
          "md5": "5dad3d4002b15cc88586263d4224a82e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jackson",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.1.1.jar",
          "url": "spring-boot-starter-jackson-4.1.1.jar",
          "size": 4740,
          "sha512": "81eecc02a6af7089dead17d6998e4cfe0b8084267de9607bdcb9c70514adf2f5bfd390d23d624bfd90f65f1a10ca5a7584529137fb86274eee634ea497ea0aab",
          "sha256": "d30e594a3e0f3a090438fc22000a87ab577a3b80c674180a10544ca331207f24",
          "sha1": "f8cd6a81994a207a808564515e5104548d1967bb",
          "md5": "5dad3d4002b15cc88586263d4224a82e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.1.1-javadoc.jar",
          "url": "spring-boot-starter-jackson-4.1.1-javadoc.jar",
          "size": 4740,
          "sha512": "81eecc02a6af7089dead17d6998e4cfe0b8084267de9607bdcb9c70514adf2f5bfd390d23d624bfd90f65f1a10ca5a7584529137fb86274eee634ea497ea0aab",
          "sha256": "d30e594a3e0f3a090438fc22000a87ab577a3b80c674180a10544ca331207f24",
          "sha1": "f8cd6a81994a207a808564515e5104548d1967bb",
          "md5": "5dad3d4002b15cc88586263d4224a82e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.1.1-sources.jar",
          "url": "spring-boot-starter-jackson-4.1.1-sources.jar",
          "size": 4740,
          "sha512": "81eecc02a6af7089dead17d6998e4cfe0b8084267de9607bdcb9c70514adf2f5bfd390d23d624bfd90f65f1a10ca5a7584529137fb86274eee634ea497ea0aab",
          "sha256": "d30e594a3e0f3a090438fc22000a87ab577a3b80c674180a10544ca331207f24",
          "sha1": "f8cd6a81994a207a808564515e5104548d1967bb",
          "md5": "5dad3d4002b15cc88586263d4224a82e"
        }
      ]
    }
  ]
}
