{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "7.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-7.0.9.jar",
          "url": "spring-test-7.0.9.jar",
          "size": 1109299,
          "sha512": "b37bc50d79b184ad0434ceeb6301f45f8cdc8bfa7574db1ea0042a11a8fd986e0d012a9f3186dcd427faeec97685d89a97098f270a3aa5e8544936f5eb392210",
          "sha256": "6ce8fc116f5d309b9ac50a6738bd1b15ea4012a4a5563c0ee89b795bfc9af0dc",
          "sha1": "6c7a684b41d69ad6e46b9bd14ad03a8ff6257adf",
          "md5": "13d80c81a2e851edd07316b698fabf26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-7.0.9.jar",
          "url": "spring-test-7.0.9.jar",
          "size": 1109299,
          "sha512": "b37bc50d79b184ad0434ceeb6301f45f8cdc8bfa7574db1ea0042a11a8fd986e0d012a9f3186dcd427faeec97685d89a97098f270a3aa5e8544936f5eb392210",
          "sha256": "6ce8fc116f5d309b9ac50a6738bd1b15ea4012a4a5563c0ee89b795bfc9af0dc",
          "sha1": "6c7a684b41d69ad6e46b9bd14ad03a8ff6257adf",
          "md5": "13d80c81a2e851edd07316b698fabf26"
        }
      ]
    }
  ]
}
