{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate-ktx",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14329657"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.4.0-sources.jar",
          "url": "savedstate-ktx-1.4.0-sources.jar",
          "size": 4426,
          "sha512": "470b68b1ba0bbefe5afcf0a072635a72e5080f040860d900c972c9797c1ab4c2402ad6a622477ea916ecc6ece19b0290e15a391f7f1a0ea00c612b1da3ea6d82",
          "sha256": "b1e8d78600a68fb3c0029793146ac07ea0335819f813554e85c568caa35cb5e4",
          "sha1": "d281a4d66d1b5ed25c21373dedb46a67918618d9",
          "md5": "c7dd8c25948273de8256385c8a05e3d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.4.0.aar",
          "url": "savedstate-ktx-1.4.0.aar",
          "size": 5764,
          "sha512": "b5ef95f1175b44c162b8f104d5885ff46aefe3c46ccabed67a5aa65a358295546fbdb3e751421ddf57276554c9cd0a4756cc4958c612f8947f51aae2d5adf0ff",
          "sha256": "23593939446bc5a154a1e35fddd87b82f19e2adf072207f115bf29a8b431c1d3",
          "sha1": "e41710c322b045e933fa8710d0c4540987574daa",
          "md5": "da1726763178d846c8b4264fdc20a293"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.4.0.aar",
          "url": "savedstate-ktx-1.4.0.aar",
          "size": 5764,
          "sha512": "b5ef95f1175b44c162b8f104d5885ff46aefe3c46ccabed67a5aa65a358295546fbdb3e751421ddf57276554c9cd0a4756cc4958c612f8947f51aae2d5adf0ff",
          "sha256": "23593939446bc5a154a1e35fddd87b82f19e2adf072207f115bf29a8b431c1d3",
          "sha1": "e41710c322b045e933fa8710d0c4540987574daa",
          "md5": "da1726763178d846c8b4264fdc20a293"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.4.0-versionMetadata.json",
          "url": "savedstate-ktx-1.4.0-versionMetadata.json",
          "size": 191,
          "sha512": "225072cf1e54fc7479700f5339019ceafe1f9e4d514a8893a626190d42dfb31b35804c73597292ee864e5f3034bc73b4c5806109ed130eb268c531948a4be4b7",
          "sha256": "ff1847220d3c526a133e4f76baed2060de09a72ac96f5b8e1fef2ab1d21ba85e",
          "sha1": "a1a2692ed79fa0caa20fafeb33e56bd48993f6de",
          "md5": "57c4eed7a9c15485d30d344fdc944a0a"
        }
      ]
    }
  ]
}