{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-1.1.7-multiplatform-sources.jar",
          "url": "datastore-preferences-1.1.7-multiplatform-sources.jar",
          "size": 7355,
          "sha512": "eb14b00cd5b444070e21e1fd887f9bfa7b78507eea81906b6de1e7bfe47a227c983f9662ff7c2167d367fd6f3856974d64b895a7858a232f86796362e1e95f3e",
          "sha256": "d1d04d5d2b62336a34d8a432048561c3f8e1b511969c25f87aa6ce1e2b3a4585",
          "sha1": "c14c79af80adedfcba4349a150e1566adc834294",
          "md5": "43e10c2ed3350324da37c85f331ce569"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "datastore-preferences-1.1.7-versionMetadata.json",
          "size": 1373,
          "sha512": "2916e08bd839df242addf074bdcf09203d7e6a3a92e333bae5e0fc64ae8f0cda27617a18f11e3b6bca39813ed56baf4ed91624e488868bf377ccceb3c33f6193",
          "sha256": "a4c0fef981d21b4d3f4329d89814db7573a35c178d0caa283656b271f6bf0b73",
          "sha1": "baa9b93e223b203babed748c066f27b6e9810618",
          "md5": "f0ac190c53108115a998d18ab9182be6"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-metadata-1.1.7.jar",
          "url": "datastore-preferences-1.1.7.jar",
          "size": 3516,
          "sha512": "a295af4b342ea4f73feab15a85253ca6687622b3bf05f85992fc46cbff332b5a66929d1803b461ae8ec9f7c65ce59c7dbadd30fd0bd0b429b2568c71c0673a8a",
          "sha256": "7daf288a2f1efe727eac9fb75d9c8a773512c654740eb8381d443439c3d0c3a1",
          "sha1": "19e08aabbf54cf4a90ff26531e5a56f020f984dc",
          "md5": "c38d27c7844282b3033074a9364ce6da"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-kotlin-1.1.7-sources.jar",
          "url": "datastore-preferences-1.1.7-sources.jar",
          "size": 1561,
          "sha512": "80d3da22059bbe0938d26c7216206c64bf15ea3d7b73d7fb4a2067e29fb35562d093c15c2789b72d77d74cc603b1700f3a2ccf3e4c44950a9fd45be8f5222cdd",
          "sha256": "5c6f68568cbaf8afcf0e319f6b1af41c72eff34d4613ff926f842e19176a0ff0",
          "sha1": "d84b71e342fdc1f84366d8598f6d7098ab0d1f81",
          "md5": "354beb71980001fe6d73ba6ea6e0894f"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-android/1.1.7/datastore-preferences-android-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-android",
        "version": "1.1.7"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-android/1.1.7/datastore-preferences-android-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-android",
        "version": "1.1.7"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-android/1.1.7/datastore-preferences-android-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-android",
        "version": "1.1.7"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-iosarm64/1.1.7/datastore-preferences-iosarm64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-iosarm64",
        "version": "1.1.7"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-iosarm64/1.1.7/datastore-preferences-iosarm64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-iosarm64",
        "version": "1.1.7"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-iosarm64/1.1.7/datastore-preferences-iosarm64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-iosarm64",
        "version": "1.1.7"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-iossimulatorarm64/1.1.7/datastore-preferences-iossimulatorarm64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-iossimulatorarm64",
        "version": "1.1.7"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-iossimulatorarm64/1.1.7/datastore-preferences-iossimulatorarm64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-iossimulatorarm64",
        "version": "1.1.7"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-iossimulatorarm64/1.1.7/datastore-preferences-iossimulatorarm64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-iossimulatorarm64",
        "version": "1.1.7"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-iosx64/1.1.7/datastore-preferences-iosx64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-iosx64",
        "version": "1.1.7"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-iosx64/1.1.7/datastore-preferences-iosx64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-iosx64",
        "version": "1.1.7"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-iosx64/1.1.7/datastore-preferences-iosx64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-iosx64",
        "version": "1.1.7"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-jvm/1.1.7/datastore-preferences-jvm-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-jvm",
        "version": "1.1.7"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-jvm/1.1.7/datastore-preferences-jvm-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-jvm",
        "version": "1.1.7"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-jvm/1.1.7/datastore-preferences-jvm-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-jvm",
        "version": "1.1.7"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-linuxx64/1.1.7/datastore-preferences-linuxx64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-linuxx64",
        "version": "1.1.7"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-linuxx64/1.1.7/datastore-preferences-linuxx64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-linuxx64",
        "version": "1.1.7"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-macosarm64/1.1.7/datastore-preferences-macosarm64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-macosarm64",
        "version": "1.1.7"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-macosarm64/1.1.7/datastore-preferences-macosarm64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-macosarm64",
        "version": "1.1.7"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-macosarm64/1.1.7/datastore-preferences-macosarm64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-macosarm64",
        "version": "1.1.7"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-macosx64/1.1.7/datastore-preferences-macosx64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-macosx64",
        "version": "1.1.7"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-macosx64/1.1.7/datastore-preferences-macosx64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-macosx64",
        "version": "1.1.7"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-macosx64/1.1.7/datastore-preferences-macosx64-1.1.7.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-macosx64",
        "version": "1.1.7"
      }
    }
  ]
}