{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14329657"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "prevents symbols duplication"
        }
      ],
      "files": [
        {
          "name": "savedstate-metadata-1.4.0.jar",
          "url": "savedstate-1.4.0.jar",
          "size": 36776,
          "sha512": "9b6e64c126776e0b3cb16f86af0e4cac9a4e65fec434f746391ad8a9d0f115a835f23ff3cc2ae1db0e5c5504a1a4cccaf3d502f1c36a1fe0da023a819dfa2988",
          "sha256": "098596c8dfba2bef44be037f3d3f89cdd011587505ed82fa625f2a83a22d6415",
          "sha1": "eeda9569d1fdadab9a0a8e323910adafeee3b2ae",
          "md5": "d13fd5324c2c16161161fb8a4d4c4ad0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-kotlin-1.4.0-sources.jar",
          "url": "savedstate-1.4.0-sources.jar",
          "size": 52666,
          "sha512": "1bbb90c6c669b301fdb8265100f4abc42ae0ad33c46e4cb685d7924e46fe1ec1ef8e948ef8dc0566967d8b09e113ab1d7bcb10e4bbbb00180ccecce270e3fa6f",
          "sha256": "02cdc0f1b8f1313ba1e22193910618edc6f7877e542d2d83cbba5d2d68d16dd5",
          "sha1": "0eaea653a0a2a8bdb6f3f8b15adcc1c9cbaf49c1",
          "md5": "5094a35df0b069f1e600adecc4e827cd"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-1.4.0-multiplatform-sources.jar",
          "url": "savedstate-1.4.0-multiplatform-sources.jar",
          "size": 76542,
          "sha512": "1ac9daa0fa610bf3f1bf8ea9dd4856ce7141c30b513942c57a6baf02464f6e88d4f397af013443bf9a5695d1732c33ccb6d9dd6d8d698696c2d00df6659cb2df",
          "sha256": "423d93fcfb218bd9bdd039e7733765ed881f43617493a719da7ed495211b2caf",
          "sha1": "ae35b56a270a6f9688c2eb52a03abd36358ef466",
          "md5": "06e55871c5c081166688b55732bd28aa"
        },
        {
          "name": "savedstate-1.4.0-samples-sources.jar",
          "url": "savedstate-1.4.0-samples-sources.jar",
          "size": 7330,
          "sha512": "f1b77905da38cc98f6efcd3f9a440b2f2e91887e64fa966f707f4613163bbbc5893f32d235b4a5e6ecea3847264af93f898d4585eee2d1f4558ed0c0545de34d",
          "sha256": "55d183dec7a7b59cfc754f1fde95262298a33ae1abc9a2554d7640ee1360ee1e",
          "sha1": "45540714f2e54e94c96da6214912c134ffcd9d32",
          "md5": "6cf2c87e40e1ebafa911b4df0300f2cb"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "savedstate-1.4.0-versionMetadata.json",
          "size": 31596,
          "sha512": "a825dbe1401ccfd30de170339b6c62c61efd307d66e454886423cfed961e72bf403edf6f8ada18d53c4d84daf4684c6c54e0faf816812ab919de84de79673fde",
          "sha256": "f87c8b689c5106784c062cb9875108530e6a999802281d8f0bb7ec6daabec458",
          "sha1": "b2ac690fd9ee106f2434d70320a6f6e62e0f4375",
          "md5": "2b8c55bb4c880f9af36ca1dc63d23e1e"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../savedstate-android/1.4.0/savedstate-android-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-android",
        "version": "1.4.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../savedstate-android/1.4.0/savedstate-android-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-android",
        "version": "1.4.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../savedstate-android/1.4.0/savedstate-android-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-android",
        "version": "1.4.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../savedstate-desktop/1.4.0/savedstate-desktop-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-desktop",
        "version": "1.4.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../savedstate-desktop/1.4.0/savedstate-desktop-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-desktop",
        "version": "1.4.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../savedstate-desktop/1.4.0/savedstate-desktop-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-desktop",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-iosarm64/1.4.0/savedstate-iosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-iosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-iosarm64/1.4.0/savedstate-iosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-iosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-iosarm64/1.4.0/savedstate-iosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-iosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-iossimulatorarm64/1.4.0/savedstate-iossimulatorarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-iossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-iossimulatorarm64/1.4.0/savedstate-iossimulatorarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-iossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-iossimulatorarm64/1.4.0/savedstate-iossimulatorarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-iossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-iosx64/1.4.0/savedstate-iosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-iosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-iosx64/1.4.0/savedstate-iosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-iosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-iosx64/1.4.0/savedstate-iosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-iosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../savedstate-js/1.4.0/savedstate-js-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../savedstate-js/1.4.0/savedstate-js-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../savedstate-js/1.4.0/savedstate-js-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-linuxarm64/1.4.0/savedstate-linuxarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-linuxarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-linuxarm64/1.4.0/savedstate-linuxarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-linuxarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-linuxx64/1.4.0/savedstate-linuxx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-linuxx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-linuxx64/1.4.0/savedstate-linuxx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-linuxx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-macosarm64/1.4.0/savedstate-macosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-macosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-macosarm64/1.4.0/savedstate-macosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-macosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-macosarm64/1.4.0/savedstate-macosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-macosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-macosx64/1.4.0/savedstate-macosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-macosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-macosx64/1.4.0/savedstate-macosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-macosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-macosx64/1.4.0/savedstate-macosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-macosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-mingwx64/1.4.0/savedstate-mingwx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-mingwx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-mingwx64/1.4.0/savedstate-mingwx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-mingwx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-tvosarm64/1.4.0/savedstate-tvosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-tvosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-tvosarm64/1.4.0/savedstate-tvosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-tvosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-tvosarm64/1.4.0/savedstate-tvosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-tvosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-tvossimulatorarm64/1.4.0/savedstate-tvossimulatorarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-tvossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-tvossimulatorarm64/1.4.0/savedstate-tvossimulatorarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-tvossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-tvossimulatorarm64/1.4.0/savedstate-tvossimulatorarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-tvossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-tvosx64/1.4.0/savedstate-tvosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-tvosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-tvosx64/1.4.0/savedstate-tvosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-tvosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-tvosx64/1.4.0/savedstate-tvosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-tvosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../savedstate-wasm-js/1.4.0/savedstate-wasm-js-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-wasm-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../savedstate-wasm-js/1.4.0/savedstate-wasm-js-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-wasm-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../savedstate-wasm-js/1.4.0/savedstate-wasm-js-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-wasm-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosarm32/1.4.0/savedstate-watchosarm32-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosarm32/1.4.0/savedstate-watchosarm32-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosarm32/1.4.0/savedstate-watchosarm32-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosarm64/1.4.0/savedstate-watchosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosarm64/1.4.0/savedstate-watchosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosarm64/1.4.0/savedstate-watchosarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosdevicearm64/1.4.0/savedstate-watchosdevicearm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosdevicearm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosdevicearm64/1.4.0/savedstate-watchosdevicearm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosdevicearm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosdevicearm64/1.4.0/savedstate-watchosdevicearm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosdevicearm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchossimulatorarm64/1.4.0/savedstate-watchossimulatorarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchossimulatorarm64/1.4.0/savedstate-watchossimulatorarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchossimulatorarm64/1.4.0/savedstate-watchossimulatorarm64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosx64/1.4.0/savedstate-watchosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosx64/1.4.0/savedstate-watchosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../savedstate-watchosx64/1.4.0/savedstate-watchosx64-1.4.0.module",
        "group": "androidx.savedstate",
        "module": "savedstate-watchosx64",
        "version": "1.4.0"
      }
    }
  ]
}