{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ads",
    "module": "ads-adservices",
    "version": "1.1.0-beta11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices-java",
          "version": {
            "requires": "1.1.0-beta11"
          },
          "reason": "ads-adservices is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-1.1.0-beta11-sources.jar",
          "url": "ads-adservices-1.1.0-beta11-sources.jar",
          "size": 100108,
          "sha512": "ed0d8f8653be9d462c68d8bb596e6d70ee2a686665ab28bd6fecf5fc4c3f07958b695749928436fe33ba2e99cd678388bcf8aed01e4fcd010445c4e884d2c341",
          "sha256": "c7982c9d74a85f30657584fe19e29c934475aa25fb16e09b132181e4639f7984",
          "sha1": "5b6e7dd5fd71c0b80185cbc0e9bb99045ddc5e9e",
          "md5": "765ab7806a09eed8043b01d5af67b4a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices-java",
          "version": {
            "requires": "1.1.0-beta11"
          },
          "reason": "ads-adservices is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-1.1.0-beta11.aar",
          "url": "ads-adservices-1.1.0-beta11.aar",
          "size": 209550,
          "sha512": "66584db2e22564045bda8d33b168c70fda28675b36b51fe17a062db62c9690f9df28ad7ae936eded66f4a19a75131eef9c535811b0aa5fae1a8bf808862e0854",
          "sha256": "540a6e2dc78e370615f77f872c0f3b700a1aca1d78a4a9af7d2808050848c663",
          "sha1": "b2da1657783591d1bc27b6d1f9cbc3303c835849",
          "md5": "eae3a2ea5cc33deac4c439295a01e368"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices-java",
          "version": {
            "requires": "1.1.0-beta11"
          },
          "reason": "ads-adservices is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-1.1.0-beta11.aar",
          "url": "ads-adservices-1.1.0-beta11.aar",
          "size": 209550,
          "sha512": "66584db2e22564045bda8d33b168c70fda28675b36b51fe17a062db62c9690f9df28ad7ae936eded66f4a19a75131eef9c535811b0aa5fae1a8bf808862e0854",
          "sha256": "540a6e2dc78e370615f77f872c0f3b700a1aca1d78a4a9af7d2808050848c663",
          "sha1": "b2da1657783591d1bc27b6d1f9cbc3303c835849",
          "md5": "eae3a2ea5cc33deac4c439295a01e368"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices-java",
          "version": {
            "requires": "1.1.0-beta11"
          },
          "reason": "ads-adservices is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-1.1.0-beta11-versionMetadata.json",
          "url": "ads-adservices-1.1.0-beta11-versionMetadata.json",
          "size": 29014,
          "sha512": "29b53204a388b7eafed02a8066f4d98034149da576eaa9df1748ad91e4b46cb01a2cd5c8953130438e04b5fc10756c575a754540d2dd07610b23f3266209ab08",
          "sha256": "f7cc465f99d64261e66fd66ad0c405bd69711c6b13a8310e8b80d3c6a52c73e3",
          "sha1": "f84c72c61305e6bcd6322d96b43012baca5faaf9",
          "md5": "efc4b92b918dff3e2d6f8989a14a74dc"
        }
      ]
    }
  ]
}