{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "fus-statistics-gradle-plugin",
    "version": "2.3.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-sources.jar",
          "size": 16568,
          "sha512": "7fd55f39c0073a280d14e89a97bc9e9df34cf3bf21c56e54f35b7d51dc26a073020ace5e2d6b150e76536a8af6c16481462cbeebed1a01bde6ebaf1096bdccab",
          "sha256": "25225642ec723c9ea8e4c493e6362d84a796476e37df6e688d9de8fb415d9048",
          "sha1": "328a022321ac3cb4b22bfc9b65e6680377688efb",
          "md5": "9c2951da30104600e5252fd842442fb0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ]
    },
    {
      "name": "gradle80JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle80-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle80-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle80SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle80-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle80-sources.jar",
          "size": 16568,
          "sha512": "7fd55f39c0073a280d14e89a97bc9e9df34cf3bf21c56e54f35b7d51dc26a073020ace5e2d6b150e76536a8af6c16481462cbeebed1a01bde6ebaf1096bdccab",
          "sha256": "25225642ec723c9ea8e4c493e6362d84a796476e37df6e688d9de8fb415d9048",
          "sha1": "328a022321ac3cb4b22bfc9b65e6680377688efb",
          "md5": "9c2951da30104600e5252fd842442fb0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle80ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle80.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle80.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle80RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle80.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle80.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle81JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle81-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle81-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle81SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle81-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle81-sources.jar",
          "size": 16568,
          "sha512": "7fd55f39c0073a280d14e89a97bc9e9df34cf3bf21c56e54f35b7d51dc26a073020ace5e2d6b150e76536a8af6c16481462cbeebed1a01bde6ebaf1096bdccab",
          "sha256": "25225642ec723c9ea8e4c493e6362d84a796476e37df6e688d9de8fb415d9048",
          "sha1": "328a022321ac3cb4b22bfc9b65e6680377688efb",
          "md5": "9c2951da30104600e5252fd842442fb0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle81ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle81.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle81.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle81RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle81.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle81.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle82JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle82-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle82-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle82SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle82-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle82-sources.jar",
          "size": 16568,
          "sha512": "7fd55f39c0073a280d14e89a97bc9e9df34cf3bf21c56e54f35b7d51dc26a073020ace5e2d6b150e76536a8af6c16481462cbeebed1a01bde6ebaf1096bdccab",
          "sha256": "25225642ec723c9ea8e4c493e6362d84a796476e37df6e688d9de8fb415d9048",
          "sha1": "328a022321ac3cb4b22bfc9b65e6680377688efb",
          "md5": "9c2951da30104600e5252fd842442fb0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle82ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle82.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle82.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle82RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle82.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle82.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle85JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle85-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle85-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle85SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle85-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle85-sources.jar",
          "size": 16568,
          "sha512": "7fd55f39c0073a280d14e89a97bc9e9df34cf3bf21c56e54f35b7d51dc26a073020ace5e2d6b150e76536a8af6c16481462cbeebed1a01bde6ebaf1096bdccab",
          "sha256": "25225642ec723c9ea8e4c493e6362d84a796476e37df6e688d9de8fb415d9048",
          "sha1": "328a022321ac3cb4b22bfc9b65e6680377688efb",
          "md5": "9c2951da30104600e5252fd842442fb0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle85ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle85.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle85.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle85RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle85.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle85.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle86JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle86-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle86-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle86SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle86-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle86-sources.jar",
          "size": 16568,
          "sha512": "7fd55f39c0073a280d14e89a97bc9e9df34cf3bf21c56e54f35b7d51dc26a073020ace5e2d6b150e76536a8af6c16481462cbeebed1a01bde6ebaf1096bdccab",
          "sha256": "25225642ec723c9ea8e4c493e6362d84a796476e37df6e688d9de8fb415d9048",
          "sha1": "328a022321ac3cb4b22bfc9b65e6680377688efb",
          "md5": "9c2951da30104600e5252fd842442fb0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle86ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle86.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle86.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle86RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle86.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle86.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle88JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle88-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle88-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle88SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle88-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle88-sources.jar",
          "size": 16568,
          "sha512": "7fd55f39c0073a280d14e89a97bc9e9df34cf3bf21c56e54f35b7d51dc26a073020ace5e2d6b150e76536a8af6c16481462cbeebed1a01bde6ebaf1096bdccab",
          "sha256": "25225642ec723c9ea8e4c493e6362d84a796476e37df6e688d9de8fb415d9048",
          "sha1": "328a022321ac3cb4b22bfc9b65e6680377688efb",
          "md5": "9c2951da30104600e5252fd842442fb0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle88ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle88.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle88.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle88RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle88.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle88.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle811JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle811-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle811-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle811SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle811-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle811-sources.jar",
          "size": 16568,
          "sha512": "7fd55f39c0073a280d14e89a97bc9e9df34cf3bf21c56e54f35b7d51dc26a073020ace5e2d6b150e76536a8af6c16481462cbeebed1a01bde6ebaf1096bdccab",
          "sha256": "25225642ec723c9ea8e4c493e6362d84a796476e37df6e688d9de8fb415d9048",
          "sha1": "328a022321ac3cb4b22bfc9b65e6680377688efb",
          "md5": "9c2951da30104600e5252fd842442fb0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle811ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle811.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle811.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle811RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle811.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle811.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle813JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle813-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle813-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle813SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle813-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle813-sources.jar",
          "size": 16568,
          "sha512": "7fd55f39c0073a280d14e89a97bc9e9df34cf3bf21c56e54f35b7d51dc26a073020ace5e2d6b150e76536a8af6c16481462cbeebed1a01bde6ebaf1096bdccab",
          "sha256": "25225642ec723c9ea8e4c493e6362d84a796476e37df6e688d9de8fb415d9048",
          "sha1": "328a022321ac3cb4b22bfc9b65e6680377688efb",
          "md5": "9c2951da30104600e5252fd842442fb0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle813ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle813.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle813.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "gradle813RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.3.21-gradle813.jar",
          "url": "fus-statistics-gradle-plugin-2.3.21-gradle813.jar",
          "size": 86426,
          "sha512": "fe29c0d391a2c8dfed9668f4ddc4c81e649619c42c8d8810efbd8386bd9ea00e68e64f484462e3aaab15b2118f66c662146183123f23ec99cea75356d23aa580",
          "sha256": "73379b384d9da66419b5f4d5c83de1a99dd7f195662bc45c39443859e63e18b2",
          "sha1": "1259208accda191a28e985bcb224c5fbed3ecee4",
          "md5": "5343fdf132afbe1fba070cc6046ed7ec"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.3.21"
        }
      ]
    }
  ]
}
