{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-test/2.2.20/kotlin-test-2.2.20.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.2.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmJUnit5ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit5-2.2.20.jar",
          "url": "kotlin-test-junit5-2.2.20.jar",
          "size": 5065,
          "sha512": "abc30a04c712923ca53d2d7bee25a0970b9e39ba51bbea797416e2a40d6adad03d103785ecd9d9706bf2bb999a6c63d97253faeeb3399cf024a61cd1b953d76b",
          "sha256": "677dcbb681b33eb5df548f16171fcedf37214302a8b2d7731a37d30cdc6a20af",
          "sha1": "49ae856307ab7fc0e35864099c0c1300976987f6",
          "md5": "0536d8de18403a44d0b15b99ec7a56ae"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit5",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "jvmJUnit5RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit5-2.2.20.jar",
          "url": "kotlin-test-junit5-2.2.20.jar",
          "size": 5065,
          "sha512": "abc30a04c712923ca53d2d7bee25a0970b9e39ba51bbea797416e2a40d6adad03d103785ecd9d9706bf2bb999a6c63d97253faeeb3399cf024a61cd1b953d76b",
          "sha256": "677dcbb681b33eb5df548f16171fcedf37214302a8b2d7731a37d30cdc6a20af",
          "sha1": "49ae856307ab7fc0e35864099c0c1300976987f6",
          "md5": "0536d8de18403a44d0b15b99ec7a56ae"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit5",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "jvmJUnit5SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-test-junit5-2.2.20-sources.jar",
          "url": "kotlin-test-junit5-2.2.20-sources.jar",
          "size": 2850,
          "sha512": "aa488b547a8587cc2cc004a3e943460a043e926a7cb021d70a3182ff05a1e7d542ba77590d9115db58d9ca1c72bf16bca1eb89fe58f46fb5a0fcf6ec2895a22f",
          "sha256": "891c56d8183d2cd3e912cf250adeca889dba51d02b07fce3015321e08f72b4a2",
          "sha1": "e7609990cba72d2a3ce763011ae79e81b9904b51",
          "md5": "6fc43e36017a96bd097f1858ff8fa394"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit5",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.2.20"
        }
      ]
    }
  ]
}