{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ads",
    "module": "ads-adservices-java",
    "version": "1.1.0-beta11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta11"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta11-sources.jar",
          "url": "ads-adservices-java-1.1.0-beta11-sources.jar",
          "size": 22958,
          "sha512": "a2dcea977f56f468fee9192a9aba6b5dd0c6203c36c98bad5fd95dcd814d6981f7105442d069dc3bffda40ac243a0e4bb2849abb2c529ddcc45c5ca05020b9f2",
          "sha256": "124bfd1e7ddc4237992d1ffa26382472df43fbf4a5a9ac08052c78a5595ecea8",
          "sha1": "a8b4b4e83aec1a938401f49f98bb3631ea37499a",
          "md5": "2202a7f68fcddd6afe2d6635d6afa53d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta11"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta11.aar",
          "url": "ads-adservices-java-1.1.0-beta11.aar",
          "size": 74620,
          "sha512": "fe22d43f98343dcc6c9fcff73c86f299b7bbe75fd40633cd35041defc0567ad937e35e37afae3022dba7507da6931a718cd0d29c9156931262cb7551152b6501",
          "sha256": "b2885db5ddad9b457f94d21041da53267da89adfe438242ba07dd11c8fa63e74",
          "sha1": "40fca4b3d41755760f76d0c3c70f26ee9a631d28",
          "md5": "4217b0b2f539cd9a4b3fb0a2c4011910"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta11"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta11"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta11.aar",
          "url": "ads-adservices-java-1.1.0-beta11.aar",
          "size": 74620,
          "sha512": "fe22d43f98343dcc6c9fcff73c86f299b7bbe75fd40633cd35041defc0567ad937e35e37afae3022dba7507da6931a718cd0d29c9156931262cb7551152b6501",
          "sha256": "b2885db5ddad9b457f94d21041da53267da89adfe438242ba07dd11c8fa63e74",
          "sha1": "40fca4b3d41755760f76d0c3c70f26ee9a631d28",
          "md5": "4217b0b2f539cd9a4b3fb0a2c4011910"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta11"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta11-versionMetadata.json",
          "url": "ads-adservices-java-1.1.0-beta11-versionMetadata.json",
          "size": 5561,
          "sha512": "4a664686aa29044e822ffde817982bb98b4e76719b6dfcfa340250519d4ed5ab857f4719806aaf47ee5b6d670db39c68d800d86f843d1927920498afddc67a85",
          "sha256": "a41ac93dc8175c95ecf2356626d6b1820b143cbf41fc2e77a35e1ba398334193",
          "sha1": "149f21e0a24c2174449c11b8817c2615a2b007eb",
          "md5": "768b17f667ddbee25c50d1b477c109ca"
        }
      ]
    }
  ]
}