{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-resttestclient",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-resttestclient-4.1.1.jar",
          "url": "spring-boot-resttestclient-4.1.1.jar",
          "size": 33556,
          "sha512": "b2a583e65d5addda7ba97a864716c21843a0e0a0f6d9c02bdb43341d8d2e342bf297f114cb2cdfebcde1a1f1095ca4cc38a99f3466e5a0f25e15ec5c765f74f3",
          "sha256": "329fc4ffc9da161a21755d2af9c92ed861d29e49b713b9e7317c8540c812c0ad",
          "sha1": "082f15f0bebacc85a80afc731f44ccc3fb81648c",
          "md5": "5b4c09ddf9c7bbc8b2eafbea7a096cdf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-resttestclient-4.1.1.jar",
          "url": "spring-boot-resttestclient-4.1.1.jar",
          "size": 33556,
          "sha512": "b2a583e65d5addda7ba97a864716c21843a0e0a0f6d9c02bdb43341d8d2e342bf297f114cb2cdfebcde1a1f1095ca4cc38a99f3466e5a0f25e15ec5c765f74f3",
          "sha256": "329fc4ffc9da161a21755d2af9c92ed861d29e49b713b9e7317c8540c812c0ad",
          "sha1": "082f15f0bebacc85a80afc731f44ccc3fb81648c",
          "md5": "5b4c09ddf9c7bbc8b2eafbea7a096cdf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-resttestclient-4.1.1-javadoc.jar",
          "url": "spring-boot-resttestclient-4.1.1-javadoc.jar",
          "size": 140663,
          "sha512": "4d1672078b6d72ad370c155b7994f97a1188e8d5b4e09c13f11e1f6b38421d25aa254514d07533abbecbd085f85d10447eb39ac00364ebb449a00dda87494ea7",
          "sha256": "4dcd8d9e43d61239377d6f79d656f91be8ecde3b42270de2b975f21065d2745a",
          "sha1": "9a213074cea545cd641eb8574cdddbf8460c88ab",
          "md5": "53d4bb0378be73c9b5964ea62a053db9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-resttestclient-4.1.1-sources.jar",
          "url": "spring-boot-resttestclient-4.1.1-sources.jar",
          "size": 22365,
          "sha512": "1db6be960fce5446220ead0abf74b07c6f041d1f809d0b948c0ea64e559829255114e222092295a8b32c385f9b3bbfed632ce1aa6825c1545a6e87fc71c83718",
          "sha256": "118f4798f7966788779f999403df5d8b37444f5edb24fbdf0d86b2d633883d4c",
          "sha1": "ce576b8ab7b156f7ab9a68237aedfcf955462750",
          "md5": "fb3f785896eaedce7ce42b0fd42dae77"
        }
      ]
    }
  ]
}
