{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "material-1.7.0-multiplatform-sources.jar",
          "url": "material-1.7.0-multiplatform-sources.jar",
          "size": 254803,
          "sha512": "222cfd712543db7af904a1b3d4a6c166a3999821672cc99ad939178b7de2fc240165fcf0a70eae4851d98138773165c63616e94aab4f9fd2e3f9aaa07c9f3fd1",
          "sha256": "7c7a5e66681390f48e9c3c9e918a7882f8af533e2793c398380aef7565be4725",
          "sha1": "efb8560dd24a5a3e5755131236784912ca4806c7",
          "md5": "83c8e13022da2cd398d0240c7bb0317c"
        },
        {
          "name": "material-1.7.0-samples-sources.jar",
          "url": "material-1.7.0-samples-sources.jar",
          "size": 45207,
          "sha512": "a04b759ccfaba8c3cbf2d322b8799e17a04731c570c61627fa3c0d353ba8794d4a28b8c12b96100d3b5cf35e6083dce85749eff12f78b0f56c169d5f217344ce",
          "sha256": "650bfced6e90fba241db7884bf3785482f41c0ae5ce4f68a7d66039e1d16339b",
          "sha1": "6ebb29bfb19a8ee27431234559e62b4c84103b07",
          "md5": "f555171c43ba4e2c91d5c46f826a3e18"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material-1.7.0-versionMetadata.json",
          "size": 90463,
          "sha512": "7d8eaa4833a04510b00db876553b8acc3b522a68b8fcbb2da2005f4edc2c8ab20809325a85003fe7d6991cc53e230b8a4b9857fc8013c5d1030c656e0f1416ef",
          "sha256": "f553578ade443e59b4cc9c8c5f2ed536c885a30f6438554890e24e04722e2960",
          "sha1": "1827ee99f0bd824ecd368e8ad6d6747ded79d472",
          "md5": "5e5f9dc23382a3eec0cee14047046318"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-metadata-1.7.0.jar",
          "url": "material-1.7.0.jar",
          "size": 782,
          "sha512": "e1d8a2884b62d5f050fc7042dd08213d0aaee6f2197791217b6e6d00367362cc2e7f3aeec9f93d71686f556431bebcd3cbadf792a01f266e6235173ce15ea520",
          "sha256": "1123148248332383b9959f989b732eb4c2f9365543468dc3d308643310756060",
          "sha1": "df021864a5fab0efaffd2d963f8548abd886270b",
          "md5": "f2dda5162cabee2a9e07903a82af594c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material-kotlin-1.7.0-sources.jar",
          "url": "material-1.7.0-sources.jar",
          "size": 224586,
          "sha512": "c13063d3e8156f8187552a1db7449d07dbbd491378359fba2c07af3f1a9900c4ff5cdeb1661f0752f4c64a0d9b072beca93d120ba632c6f44120b234e79fd576",
          "sha256": "d8b7831068728997f1d55b5c3b808e5c91c3e8acca024d81b6d3d7f4869fbf1f",
          "sha1": "4e5c15d2ee8c43ba8e9819b8a0d91f492fe6c667",
          "md5": "1dfa45a1d59b26ae98575031cb3b3cd9"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-android/1.7.0/material-android-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-android/1.7.0/material-android-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-android/1.7.0/material-android-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-desktop/1.7.0/material-desktop-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-desktop/1.7.0/material-desktop-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-desktop/1.7.0/material-desktop-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-desktop",
        "version": "1.7.0"
      }
    }
  ]
}