{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.1.1.jar",
          "url": "spring-boot-starter-tomcat-4.1.1.jar",
          "size": 4764,
          "sha512": "40cbb43592dd073b3471a5072c029cafaafdb6fd45d43314901e6dfff3e316fc995443ab93e564f8c4910eb66bbbc11b5886a4aca6f8d8223b236a5bf77411cc",
          "sha256": "f224d8504be3b413825ee85ef549a7b1598ee8512e062c6bd5ddce1043cd388a",
          "sha1": "8a7b2b2fd2ec40ed7e56359fb68c9a8b5fde315c",
          "md5": "da4fd524d53460ee9872627f37d82955"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.1.1.jar",
          "url": "spring-boot-starter-tomcat-4.1.1.jar",
          "size": 4764,
          "sha512": "40cbb43592dd073b3471a5072c029cafaafdb6fd45d43314901e6dfff3e316fc995443ab93e564f8c4910eb66bbbc11b5886a4aca6f8d8223b236a5bf77411cc",
          "sha256": "f224d8504be3b413825ee85ef549a7b1598ee8512e062c6bd5ddce1043cd388a",
          "sha1": "8a7b2b2fd2ec40ed7e56359fb68c9a8b5fde315c",
          "md5": "da4fd524d53460ee9872627f37d82955"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.1.1-javadoc.jar",
          "url": "spring-boot-starter-tomcat-4.1.1-javadoc.jar",
          "size": 4764,
          "sha512": "40cbb43592dd073b3471a5072c029cafaafdb6fd45d43314901e6dfff3e316fc995443ab93e564f8c4910eb66bbbc11b5886a4aca6f8d8223b236a5bf77411cc",
          "sha256": "f224d8504be3b413825ee85ef549a7b1598ee8512e062c6bd5ddce1043cd388a",
          "sha1": "8a7b2b2fd2ec40ed7e56359fb68c9a8b5fde315c",
          "md5": "da4fd524d53460ee9872627f37d82955"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.1.1-sources.jar",
          "url": "spring-boot-starter-tomcat-4.1.1-sources.jar",
          "size": 4764,
          "sha512": "40cbb43592dd073b3471a5072c029cafaafdb6fd45d43314901e6dfff3e316fc995443ab93e564f8c4910eb66bbbc11b5886a4aca6f8d8223b236a5bf77411cc",
          "sha256": "f224d8504be3b413825ee85ef549a7b1598ee8512e062c6bd5ddce1043cd388a",
          "sha1": "8a7b2b2fd2ec40ed7e56359fb68c9a8b5fde315c",
          "md5": "da4fd524d53460ee9872627f37d82955"
        }
      ]
    }
  ]
}
