{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-web-server",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.1.1.jar",
          "url": "spring-boot-web-server-4.1.1.jar",
          "size": 171647,
          "sha512": "4f9794e9aeea37debbe09662ee5fde9a7ed7c815d5ab3860a9d987499ce3cea5667dd4e6514fbab8c6c7b869b46ee3ec80dc1d8f3c3cb98c91e534d4e258358e",
          "sha256": "6912fb1fdf7f657a61ac050760fa835fb1e7496399291697e2901f82887a4fee",
          "sha1": "d1eb8e523013ac3939ae59adc5335a3de704d11b",
          "md5": "a060efd710429298574e5f7615e4f6df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.1.1.jar",
          "url": "spring-boot-web-server-4.1.1.jar",
          "size": 171647,
          "sha512": "4f9794e9aeea37debbe09662ee5fde9a7ed7c815d5ab3860a9d987499ce3cea5667dd4e6514fbab8c6c7b869b46ee3ec80dc1d8f3c3cb98c91e534d4e258358e",
          "sha256": "6912fb1fdf7f657a61ac050760fa835fb1e7496399291697e2901f82887a4fee",
          "sha1": "d1eb8e523013ac3939ae59adc5335a3de704d11b",
          "md5": "a060efd710429298574e5f7615e4f6df"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.1.1-javadoc.jar",
          "url": "spring-boot-web-server-4.1.1-javadoc.jar",
          "size": 415473,
          "sha512": "6a8530a0697d0ab9480c04dc95b4533206a16f81ad658cfbe60159086cfd851064caff6a87924bc0bc660ab6a880564732b0e87e59adb95033ca5a470d224fee",
          "sha256": "951e36cf9a1ccb6507703ee43c0cf3cd68771cc23f334027e574e659a6317083",
          "sha1": "e79d7162092ffd69719f5ed85648ad837e318c3a",
          "md5": "355490f8b04720c355919832eb85655e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.1.1-sources.jar",
          "url": "spring-boot-web-server-4.1.1-sources.jar",
          "size": 129980,
          "sha512": "9046d00daa14df0bb79c2e598071813682b9e2dc0ba5663d2397074f1f3ed717ca408c99cdcb9bf97cb85cce98cc3953c95e12db4b07bf425dc2311d3e536ac9",
          "sha256": "564fd546fc065c5563dd6f9d3ff3b1a15bb676d1104d7e2183b6bc37a2dab147",
          "sha1": "88ac16e12add725ce95386891a96821135649f12",
          "md5": "314fc784e0f717e821f9456c346b9629"
        }
      ]
    }
  ]
}
