{
  "formatVersion": "1.1",
  "component": {
    "group": "tools.jackson.module",
    "module": "jackson-module-kotlin",
    "version": "3.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "tools.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "3.1.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-kotlin-3.1.5.jar",
          "url": "jackson-module-kotlin-3.1.5.jar",
          "size": 219380,
          "sha512": "9c081526d51a405e4c58dd693d32504ad585d62d4c4f7858fddafff8fb26aa8f26c8d683ddc17243e4c35343c2daaf3efcc70fe3a405b043d4fdf2ea0096c06f",
          "sha256": "e1dedb52b0f41a014056a40c8e91e27c46b38f867681d2d42f58880d206c7055",
          "sha1": "aecfb1eb42163cb1c8936e58bdf0bece2c02e25f",
          "md5": "7e8e3371de2d9cb3103c70e696c3fc76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "tools.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "3.1.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-kotlin-3.1.5.jar",
          "url": "jackson-module-kotlin-3.1.5.jar",
          "size": 219380,
          "sha512": "9c081526d51a405e4c58dd693d32504ad585d62d4c4f7858fddafff8fb26aa8f26c8d683ddc17243e4c35343c2daaf3efcc70fe3a405b043d4fdf2ea0096c06f",
          "sha256": "e1dedb52b0f41a014056a40c8e91e27c46b38f867681d2d42f58880d206c7055",
          "sha1": "aecfb1eb42163cb1c8936e58bdf0bece2c02e25f",
          "md5": "7e8e3371de2d9cb3103c70e696c3fc76"
        }
      ]
    }
  ]
}
