{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.amqp",
    "module": "spring-amqp-bom",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.springframework.amqp",
          "module": "spring-amqp",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-amqp-client",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit-junit",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit-stream",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit-test",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbitmq-client",
          "version": {
            "requires": "4.1.1"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.springframework.amqp",
          "module": "spring-amqp",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-amqp-client",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit-junit",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit-stream",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit-test",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbitmq-client",
          "version": {
            "requires": "4.1.1"
          }
        }
      ]
    }
  ]
}
