{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webmvc",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.1.1.jar",
          "url": "spring-boot-starter-webmvc-4.1.1.jar",
          "size": 4749,
          "sha512": "d397cb60e9fb58d31d0dbe7e344084bedd4e99597955f438dee63128a928443723141ac7cbf450082c6764f62e0d386bfa6696faa1346257e519b2dd19a15765",
          "sha256": "4aec3edbdf6317fefe23db1b989d8bba143a45a51c1fc32346146ecebf67d625",
          "sha1": "7d25a0b22f776c7cc0cc18a88188113400b2b011",
          "md5": "e728f7d6e9e844dc5f76c024307d767c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.1.1.jar",
          "url": "spring-boot-starter-webmvc-4.1.1.jar",
          "size": 4749,
          "sha512": "d397cb60e9fb58d31d0dbe7e344084bedd4e99597955f438dee63128a928443723141ac7cbf450082c6764f62e0d386bfa6696faa1346257e519b2dd19a15765",
          "sha256": "4aec3edbdf6317fefe23db1b989d8bba143a45a51c1fc32346146ecebf67d625",
          "sha1": "7d25a0b22f776c7cc0cc18a88188113400b2b011",
          "md5": "e728f7d6e9e844dc5f76c024307d767c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.1.1-javadoc.jar",
          "url": "spring-boot-starter-webmvc-4.1.1-javadoc.jar",
          "size": 4749,
          "sha512": "d397cb60e9fb58d31d0dbe7e344084bedd4e99597955f438dee63128a928443723141ac7cbf450082c6764f62e0d386bfa6696faa1346257e519b2dd19a15765",
          "sha256": "4aec3edbdf6317fefe23db1b989d8bba143a45a51c1fc32346146ecebf67d625",
          "sha1": "7d25a0b22f776c7cc0cc18a88188113400b2b011",
          "md5": "e728f7d6e9e844dc5f76c024307d767c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.1.1-sources.jar",
          "url": "spring-boot-starter-webmvc-4.1.1-sources.jar",
          "size": 4749,
          "sha512": "d397cb60e9fb58d31d0dbe7e344084bedd4e99597955f438dee63128a928443723141ac7cbf450082c6764f62e0d386bfa6696faa1346257e519b2dd19a15765",
          "sha256": "4aec3edbdf6317fefe23db1b989d8bba143a45a51c1fc32346146ecebf67d625",
          "sha1": "7d25a0b22f776c7cc0cc18a88188113400b2b011",
          "md5": "e728f7d6e9e844dc5f76c024307d767c"
        }
      ]
    }
  ]
}
