{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-1.7.0-multiplatform-sources.jar",
          "url": "ui-util-1.7.0-multiplatform-sources.jar",
          "size": 15246,
          "sha512": "07ec40ade9e3a2c7a4591794e7fd36c1288df7bb203e5a9cb7d19394356792261de7cd9737498ef2542c22cb97a39d4c3c03adeb93af3bc68caa912595c3718f",
          "sha256": "2918f5488fb3947fba75886cd758ca6a97050ec1447ddf3dad3c386df90111f3",
          "sha1": "acb03199bd6ea889abd21c95912a7a16066eebbb",
          "md5": "1e97218c82b9044d2d4555149c51d45f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-util-1.7.0-versionMetadata.json",
          "size": 6011,
          "sha512": "f16a20b060b4286de784ffd19f13599b58aa3b621d733e2c1f0c008b0198d440d96a978a50882a695aba592b00e56b82c06cf94327733abeeb44f9c495ca9696",
          "sha256": "c119bf1ddd7bfb9f227bae7540fa72b0cdb21ba1fc7106e0494dc57dbfe477d2",
          "sha1": "85b36da3a0edbde01ff6165e7ee91186944ef0b0",
          "md5": "aac9f314c036510ffac7fb929d0065e0"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-metadata-1.7.0.jar",
          "url": "ui-util-1.7.0.jar",
          "size": 686,
          "sha512": "3670896f9db064a294104884c88b87c16a74bda01b7d4a27a9a57e66098e0ecaafc2df156b820030fc3b03a8d1600116006377fd3efc0f5ee41a1aefd784545e",
          "sha256": "00421ed4ed83f8b1ef2a22434a6c7102bb08e16b2cc4acfda503da9ddc213e91",
          "sha1": "62eb93f6962892bbee14e30bae1deef051d38845",
          "md5": "2569cf553a2f2e71a0c5ea1c5d7a87e2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-kotlin-1.7.0-sources.jar",
          "url": "ui-util-1.7.0-sources.jar",
          "size": 12222,
          "sha512": "3021961ce3ac99dab9e894c999b90446e4de30435fcf4dc5783d9913255a354bdf3a48e4d6b75ee8547f8096634b99d65735fef63c7e03ef7635843cf83c8871",
          "sha256": "7b05ab5128b7f6afcbd9cba98b2cf0351125e2fbc87bf870c61219d93328aed6",
          "sha1": "7a2595ae990075134e89cf9a1d68cc7fcca9002b",
          "md5": "b529c7fda5e6fe9c85b29228f3d2442e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-util-android/1.7.0/ui-util-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-util-android/1.7.0/ui-util-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-util-android/1.7.0/ui-util-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-util-desktop/1.7.0/ui-util-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-util-desktop/1.7.0/ui-util-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-util-desktop/1.7.0/ui-util-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-desktop",
        "version": "1.7.0"
      }
    }
  ]
}