{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-runtime-compose/2.10.0/lifecycle-runtime-compose-2.10.0.module",
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose",
    "version": "2.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14428372"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose.aar",
          "url": "lifecycle-runtime-compose-android-2.10.0.aar",
          "size": 1051246,
          "sha512": "23ce18cec69fd7b7df19f4ce71445641eaa5a9b42942a933ac0f56cf6510e48cc0ec078a8304e9261df631809d0339123a6aea3bb038b2942339328ec60ce59e",
          "sha256": "46e996d526829596f6db4626169a967f056fde7103507ff596bcd177b73c3675",
          "sha1": "8017df86b60b6d7ad5424d1233409be37797ef2b",
          "md5": "7d14a3b660cb1e14ab570de9415c3112"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.5"
          },
          "reason": "prevents symbols duplication"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose.aar",
          "url": "lifecycle-runtime-compose-android-2.10.0.aar",
          "size": 1051246,
          "sha512": "23ce18cec69fd7b7df19f4ce71445641eaa5a9b42942a933ac0f56cf6510e48cc0ec078a8304e9261df631809d0339123a6aea3bb038b2942339328ec60ce59e",
          "sha256": "46e996d526829596f6db4626169a967f056fde7103507ff596bcd177b73c3675",
          "sha1": "8017df86b60b6d7ad5424d1233409be37797ef2b",
          "md5": "7d14a3b660cb1e14ab570de9415c3112"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-runtime-compose is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-android-2.10.0-sources.jar",
          "url": "lifecycle-runtime-compose-android-2.10.0-sources.jar",
          "size": 17665,
          "sha512": "27ee07f02058518d4a0a069d2b3308d434078ffbc29615ab6a999e6403432474b4822d7f40c19bb53026b9440b5ae7039d0e7aa209b2b724c9a5203b2c24ae5e",
          "sha256": "37d2116e5b1c76292cf2406293d5e5210c6cf100be0020c0034a4f58e7e881dd",
          "sha1": "200586e748ad444863c2e12fafb6dbe9aa6b9675",
          "md5": "b2ce0f41c02a5b1c30a751ca531f7e92"
        },
        {
          "name": "lifecycle-runtime-compose-2.10.0-samples-sources.jar",
          "url": "lifecycle-runtime-compose-android-2.10.0-samples-sources.jar",
          "size": 8259,
          "sha512": "cda2781d2e6fd3f92ce843e4c2ce262bb8485efd7d1f23c7960b4d17c4af025dce994298dce315eec1aef3bcb6124f8b475efeae34aaf342325a8c0776bb06ed",
          "sha256": "a704d9a7753899d7fa191e6403cc2bd99e45312a6222794382cddaae81730471",
          "sha1": "a2f06f577047b2ac45888c9093ec975b3e196c3d",
          "md5": "b736d9791b3422661234b3623a9e15ef"
        }
      ]
    }
  ]
}