{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-servlet",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-servlet-4.1.1.jar",
          "url": "spring-boot-servlet-4.1.1.jar",
          "size": 47081,
          "sha512": "9c75db94c7082ef0692df36e00d24a5779a206470885e3601e8f641828255aa18c0e44159e854067929c0011aaabdb79865a16104f0c9f329a03b7a750d952e2",
          "sha256": "4dcb156e311a4c1ad5f1ed7eabd94a78ea74510b05c429a4fcfdcf8beb9d5882",
          "sha1": "76881b573c8639708ce3d520b428209335f007fc",
          "md5": "d496b25e22cd17f4f89e6a54a1f9b6f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-servlet-4.1.1.jar",
          "url": "spring-boot-servlet-4.1.1.jar",
          "size": 47081,
          "sha512": "9c75db94c7082ef0692df36e00d24a5779a206470885e3601e8f641828255aa18c0e44159e854067929c0011aaabdb79865a16104f0c9f329a03b7a750d952e2",
          "sha256": "4dcb156e311a4c1ad5f1ed7eabd94a78ea74510b05c429a4fcfdcf8beb9d5882",
          "sha1": "76881b573c8639708ce3d520b428209335f007fc",
          "md5": "d496b25e22cd17f4f89e6a54a1f9b6f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-servlet-4.1.1-javadoc.jar",
          "url": "spring-boot-servlet-4.1.1-javadoc.jar",
          "size": 216237,
          "sha512": "7736121952087f6f4da4c7a78e04f118fedc80c1eae5003cc4c3f138c6503a9c47c741ea5c4bd972fcf17acc3793af3fb4c16918fc0ebb2bc286921bb78a19ce",
          "sha256": "ca2a6d234a3d311bf75058a75b6f654e5cc0e9885e9f9a76ea200a1a483b0674",
          "sha1": "9117acd8318880e6813d82dd3307d9bd61cb4eed",
          "md5": "3d73854308aa4cd41b0eef5217769aa8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-servlet-4.1.1-sources.jar",
          "url": "spring-boot-servlet-4.1.1-sources.jar",
          "size": 44499,
          "sha512": "ff8235c575710483083905a776b3b129ca119dc6b3776f3284071e0d8a454926495384fa69467a66ad6e6da2e86e81a74490b107bcf0a58289917bf5d9a5a3bf",
          "sha256": "2fbbcff4e9a555ed8cf148aadd5df5f69fe83ca98f3f1d93fd75f5669ed4b850",
          "sha1": "40158dacd6ac1eda53d40aeb31a9936f10a63a0f",
          "md5": "c4710828fcfc0d7f06c08ccca484d797"
        }
      ]
    }
  ]
}
