{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jackson-test",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-test-4.1.1.jar",
          "url": "spring-boot-starter-jackson-test-4.1.1.jar",
          "size": 4744,
          "sha512": "a83816a4f442daa5c428a28e86a8931385bbbcc1d9aad6297c71460633dd61da95488630d5b0ab6db28777d9cf8d8d32f8646a1458a43e465fe04699b2a7b3a6",
          "sha256": "21c1ad3c8d0a04fdaef819559b1c405a0a9719076560bb4b0e3c4adf3ddb796a",
          "sha1": "078ce2c2dcdd85bdc092f2a948d7407227a25dd2",
          "md5": "a1bffd8b22c373eba541d20b6c9f9b67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-test-4.1.1.jar",
          "url": "spring-boot-starter-jackson-test-4.1.1.jar",
          "size": 4744,
          "sha512": "a83816a4f442daa5c428a28e86a8931385bbbcc1d9aad6297c71460633dd61da95488630d5b0ab6db28777d9cf8d8d32f8646a1458a43e465fe04699b2a7b3a6",
          "sha256": "21c1ad3c8d0a04fdaef819559b1c405a0a9719076560bb4b0e3c4adf3ddb796a",
          "sha1": "078ce2c2dcdd85bdc092f2a948d7407227a25dd2",
          "md5": "a1bffd8b22c373eba541d20b6c9f9b67"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-test-4.1.1-javadoc.jar",
          "url": "spring-boot-starter-jackson-test-4.1.1-javadoc.jar",
          "size": 4744,
          "sha512": "a83816a4f442daa5c428a28e86a8931385bbbcc1d9aad6297c71460633dd61da95488630d5b0ab6db28777d9cf8d8d32f8646a1458a43e465fe04699b2a7b3a6",
          "sha256": "21c1ad3c8d0a04fdaef819559b1c405a0a9719076560bb4b0e3c4adf3ddb796a",
          "sha1": "078ce2c2dcdd85bdc092f2a948d7407227a25dd2",
          "md5": "a1bffd8b22c373eba541d20b6c9f9b67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-test-4.1.1-sources.jar",
          "url": "spring-boot-starter-jackson-test-4.1.1-sources.jar",
          "size": 4744,
          "sha512": "a83816a4f442daa5c428a28e86a8931385bbbcc1d9aad6297c71460633dd61da95488630d5b0ab6db28777d9cf8d8d32f8646a1458a43e465fe04699b2a7b3a6",
          "sha256": "21c1ad3c8d0a04fdaef819559b1c405a0a9719076560bb4b0e3c4adf3ddb796a",
          "sha1": "078ce2c2dcdd85bdc092f2a948d7407227a25dd2",
          "md5": "a1bffd8b22c373eba541d20b6c9f9b67"
        }
      ]
    }
  ]
}
