{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "14122761"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-metadata-1.9.2.jar",
          "url": "foundation-1.9.2.jar",
          "size": 373185,
          "sha512": "4043d98a79ea3d1810e3856601be75517d532173e3d6625d330a5f4a8d1e680b4a5702b1faa78f3f1b8c8b6156d302392c85167d0cee6b57638bfb09cd8133ac",
          "sha256": "60bd800a8ea375412ad069088d1d55ba344c73a174e2ae4a06d22a18e4b0cfdd",
          "sha1": "09d18f0e2de41926d583e81fa201e70c348d83e3",
          "md5": "810677543c93463a2660f7c0b33592fd"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-kotlin-1.9.2-sources.jar",
          "url": "foundation-1.9.2-sources.jar",
          "size": 902563,
          "sha512": "877ba44776e85d2f82965da1b048bdc230d363e391c38cbab5068b7f362bd8647c799abb5d2dc126fb41f2f2fa9995f4b0d74f67004e3b1a845eaa79782cc1e1",
          "sha256": "2db380fe1344d7c67cab7c313afc86ca118e75dddd5012c5f4e3cd446bc525c3",
          "sha1": "c303b132818cac9d8c0dced6ca0a0c8a34444731",
          "md5": "485244a2522bf4e696779b7b589f3782"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-1.9.2-multiplatform-sources.jar",
          "url": "foundation-1.9.2-multiplatform-sources.jar",
          "size": 1045135,
          "sha512": "00d66401d21ad6b7fc965c3167ad57724a4f2361fdefb9dfed074156277fd7a9cb3ce8808a8254a3e74aefa276880d54c99fd54af9bbc0d1cac17c03ab38c0ce",
          "sha256": "8ee7c789606204093ac00273ee7047c11780034147325c0db4e9f636bb6a69cc",
          "sha1": "44e10a4d99d6882bf2f4d656e3a788d962e94104",
          "md5": "1bc0fce8384cbd9180dce24f7b59bfa5"
        },
        {
          "name": "foundation-1.9.2-samples-sources.jar",
          "url": "foundation-1.9.2-samples-sources.jar",
          "size": 87172,
          "sha512": "f6c6d56b83660a019e4df6edcacbd1503633990e8304262a14dfe6461f257aac525f8a5b3d2bfae498cab0410d5c1827a1fff79f74c4b0bcc6b470ee75f70549",
          "sha256": "9e80439b49c764cdcae2e74a1bba214a85fba0deaac672dd668a4eafcbfeda9f",
          "sha1": "927d417e21c50f15cd7f4a7c24433b7688d91f30",
          "md5": "e9cc244f25e0b12eb772bfbdc5bb9d14"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "foundation-1.9.2-versionMetadata.json",
          "size": 270795,
          "sha512": "144939be13c6bef95541e1d372fbf05a21e98fea60abf8f02d147ec251187032dbaf1c56c54a40f080d0c84649c521fef80533e3a959135363dfbfc9ab3c340d",
          "sha256": "95dd5200e6cb2c8789cc0321739dab96cac1dab2184f024ac4e3a778ad9c0d03",
          "sha1": "a159e8f83b9a6c2980ea5535dc6bfcb1bc2369f5",
          "md5": "858a9066f3f47fe5307d6e4e89842448"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.9.2/foundation-android-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.9.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.9.2/foundation-android-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.9.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.9.2/foundation-android-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.9.2"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-jvmstubs/1.9.2/foundation-jvmstubs-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-jvmstubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-jvmstubs/1.9.2/foundation-jvmstubs-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-jvmstubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-jvmstubs/1.9.2/foundation-jvmstubs-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-jvmstubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-linuxx64stubs/1.9.2/foundation-linuxx64stubs-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-linuxx64stubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-linuxx64stubs/1.9.2/foundation-linuxx64stubs-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-linuxx64stubs",
        "version": "1.9.2"
      }
    }
  ]
}