{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-webmvc-test",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webmvc-test-4.1.1.jar",
          "url": "spring-boot-webmvc-test-4.1.1.jar",
          "size": 45816,
          "sha512": "619ba8d2b23457e174297ba00471094231de2daddc2b57343cf675609cb477eae06f81f38769476d4c4bc762c7b7cf61aefe0b3c69e568556b386dfaad5e0b3d",
          "sha256": "46811c1d4307e9d54e9f41aaab69cea79d9785f2ba4257b92375a7621b35dfea",
          "sha1": "1efa2dd846aa2bba1d25b044eaaafc48233ee582",
          "md5": "80c03156faab2d98ff4bddcf3bbee6ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webmvc-test-4.1.1.jar",
          "url": "spring-boot-webmvc-test-4.1.1.jar",
          "size": 45816,
          "sha512": "619ba8d2b23457e174297ba00471094231de2daddc2b57343cf675609cb477eae06f81f38769476d4c4bc762c7b7cf61aefe0b3c69e568556b386dfaad5e0b3d",
          "sha256": "46811c1d4307e9d54e9f41aaab69cea79d9785f2ba4257b92375a7621b35dfea",
          "sha1": "1efa2dd846aa2bba1d25b044eaaafc48233ee582",
          "md5": "80c03156faab2d98ff4bddcf3bbee6ab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webmvc-test-4.1.1-javadoc.jar",
          "url": "spring-boot-webmvc-test-4.1.1-javadoc.jar",
          "size": 149717,
          "sha512": "db644ee08fa92ced55483e27c200cea29414516799c8d31cb768878b394701d2cbed75d89660223616e96b2eac143c4855466bd99cbe7a3db319eb394ca7d3a1",
          "sha256": "d133a7c1ea25b7ba6c8daead14ac037cd020a3c6a7d39f73ee403a180c6bab63",
          "sha1": "95c5095dba012e98fc41db7f8489a822a817590d",
          "md5": "d5fb39b01a81fba7c5082da51ea8097f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webmvc-test-4.1.1-sources.jar",
          "url": "spring-boot-webmvc-test-4.1.1-sources.jar",
          "size": 33399,
          "sha512": "f7ea67f9cc72c77a8bd539b2d37f21d934505fb05e218d3c5d90860940d75f3b81af7e0f9b1cf1c4834d707b3a0a061714b77fd33119cd864c3b21138697dd48",
          "sha256": "40277eb7d90a188b05e580d92005861b95d3457f8b10cddf9d2b4abb57252a11",
          "sha1": "aaddd7c324d0c4167014a84285d9fc6d842aba7a",
          "md5": "e9ad78498f9d0880f9d2d79b593278ff"
        }
      ]
    }
  ]
}
