{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-annotation/1.9.2/runtime-annotation-1.9.2.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-annotation",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "14122761"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-annotation.aar",
          "url": "runtime-annotation-android-1.9.2.aar",
          "size": 9072,
          "sha512": "919c85e21f5c67fcf208c6cbceb01d4648eaf1461287c75585a29cf8e6ca96342981ea1048a5b9f5f3640c795601160d0f1d18891e22d1de25c3034765d5f233",
          "sha256": "b5ad9d5a3adf5b7fc81eb8f8d53b4dc79f2252d66ced3e26277d29a92e9e01ac",
          "sha1": "9b9ccc782339d82890ba1265dc001aa5fbe613bd",
          "md5": "2c54568180372e53e0fec39a03fbfe0a"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-annotation.aar",
          "url": "runtime-annotation-android-1.9.2.aar",
          "size": 9072,
          "sha512": "919c85e21f5c67fcf208c6cbceb01d4648eaf1461287c75585a29cf8e6ca96342981ea1048a5b9f5f3640c795601160d0f1d18891e22d1de25c3034765d5f233",
          "sha256": "b5ad9d5a3adf5b7fc81eb8f8d53b4dc79f2252d66ced3e26277d29a92e9e01ac",
          "sha1": "9b9ccc782339d82890ba1265dc001aa5fbe613bd",
          "md5": "2c54568180372e53e0fec39a03fbfe0a"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-annotation-android-1.9.2-sources.jar",
          "url": "runtime-annotation-android-1.9.2-sources.jar",
          "size": 11556,
          "sha512": "1c729f1a9b9d418b316828c154ac787aea25610290c0f523a3926b7a08f38ead06d0796444ce415aab960f433ed0ec34378e41f8cbead99df5eb5e995da7db3c",
          "sha256": "7295f7ea24a5d238eca4cfa6e5aa009436870b1607cd554d39e4981de976c374",
          "sha1": "93909912f3419b0d21e3f17c8be94a15885d59c2",
          "md5": "e399429188d9e762a2163568360d2bcc"
        },
        {
          "name": "runtime-annotation-1.9.2-samples-sources.jar",
          "url": "runtime-annotation-android-1.9.2-samples-sources.jar",
          "size": 6132,
          "sha512": "e91df26f47eae05520743a16fcbfeb1d206772dea180805eb6a8087ff486a331ee732dc964f00b54b49bbad86d85befb51a642a0826dfdad054db9f4bd3095c3",
          "sha256": "728e5ed27524324dc79b771f67891f711058041ef3d6b805edbe0e4c0fea3fd4",
          "sha1": "7f2edc491e066e09b04bcb56725b8eacb21ed045",
          "md5": "87b2c17252a543f8eb8c4573978f8d77"
        }
      ]
    }
  ]
}