{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "14122761"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-metadata-1.9.2.jar",
          "url": "foundation-layout-1.9.2.jar",
          "size": 47869,
          "sha512": "e71316f2711293888013f4591036224e7aa608132bf736ccf4cefc25bf277531f86e311092af3e27a56601c6055f30c3e5d704e829869830de806fbec04d6e5f",
          "sha256": "75b44e51947c8ff496e2595d6142c065ff50dbb743973f54d3f8cb6022ee5cb7",
          "sha1": "cfdf2605bbd872a5cfbfec4173f27ce64ed7cc3c",
          "md5": "ee688d1ac0f5548dea621256acc7524e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-kotlin-1.9.2-sources.jar",
          "url": "foundation-layout-1.9.2-sources.jar",
          "size": 94815,
          "sha512": "d1908887d74b257cb81b9d89dc8620a2cd0536ed46c7d8b6fb174bffb8ded5ff0a068f5904b2ecfbff64c5954271559116dbed85ec174b1fcc0bf23307aa5259",
          "sha256": "66617455cf24272be3199bf91be93a211722e6e025183756afeeb772eb28f366",
          "sha1": "dd7d1f33dc2333034eb7b8ca0810e0a3458b1053",
          "md5": "a22453edf84b49b73a06d5c2e3ff5e2e"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-1.9.2-multiplatform-sources.jar",
          "url": "foundation-layout-1.9.2-multiplatform-sources.jar",
          "size": 108502,
          "sha512": "ce396d35940425e4a98d3c8a3af76cdc433e0a308acacab98eef45e159fdd5fc7e2aaeb722cb6bda33be15aa85c6bd5d47a383900df578db70e81c748dcb3012",
          "sha256": "c4fabf9890681d6de416dd35a4e02fabe5a8264ad5e0ffe76116b84d06590d6d",
          "sha1": "386ee43ddfad253db5dc00900e2ae76df7ec338a",
          "md5": "42e351644868e3b3a385f655cd335725"
        },
        {
          "name": "foundation-layout-1.9.2-samples-sources.jar",
          "url": "foundation-layout-1.9.2-samples-sources.jar",
          "size": 32462,
          "sha512": "e7b041cbea40e601edbf342cd3ade516841a076ab97f1158b1df9f58e4d5f5d5906bc42f7286e1dbf6ad302d69e277fe65cd7ba6cc4bbf487a65e3b9c9249264",
          "sha256": "0d6c4ce79232dd01c1d5321436598c5fcfad349f075b1bb655f420e0a8f745ba",
          "sha1": "d11ffc32b63523b42e060501814ca1b3c060c9f6",
          "md5": "ac6f89ae92fe8a65ef7cdf26b6ca0d98"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "foundation-layout-1.9.2-versionMetadata.json",
          "size": 50272,
          "sha512": "0d19a4661bdd783654b4fa1f7680572f68482d6fc7c86c53a5866e1ec13e14b1835272fa02ba82b77befecde432e899a19fc1f3e362351a86032a8d8f90012ed",
          "sha256": "5f4990d90f1744ec440622cc79277682c54820f7233ed53cc0d52d58563ec0e8",
          "sha1": "e9606e03c7caf6baec2556d62fa146982f67d6eb",
          "md5": "d29dbc1d800f48c4f040cdef3bbb31ff"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.9.2/foundation-layout-android-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.9.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.9.2/foundation-layout-android-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.9.2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.9.2/foundation-layout-android-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.9.2"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-jvmstubs/1.9.2/foundation-layout-jvmstubs-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-jvmstubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-jvmstubs/1.9.2/foundation-layout-jvmstubs-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-jvmstubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-jvmstubs/1.9.2/foundation-layout-jvmstubs-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-jvmstubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-layout-linuxx64stubs/1.9.2/foundation-layout-linuxx64stubs-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-linuxx64stubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-layout-linuxx64stubs/1.9.2/foundation-layout-linuxx64stubs-1.9.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-linuxx64stubs",
        "version": "1.9.2"
      }
    }
  ]
}