{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.webkit",
    "module": "webkit",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0",
      "buildId:": "16002132"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webkit-1.17.0-sources.jar",
          "url": "webkit-1.17.0-sources.jar",
          "size": 297508,
          "sha512": "fe37b4ab2c31677b17958f0cb9ee16d77f98a55a2ffc456fc8804e7c3fe4434781f562d57119fc8f819e537923a50e380ed849b2b779b674f1a1bf61f78bf084",
          "sha256": "1fc3abdfcc179717f0a1b0b8634175afe4d84ba5938eba1df75128397663ebea",
          "sha1": "0e59a1b3dc2d35a05efded653d4f7d59f6ad831a",
          "md5": "d17202bceb4b70df99a3c49d2131444a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.17.0.aar",
          "url": "webkit-1.17.0.aar",
          "size": 292667,
          "sha512": "929d3a7425896f94cdbe2a561da5a4cd7cb2fdfb258ace2f0cc4a43bffcb35117db060e439baa97442fec1029f74c39d4f0c073778408e7cc9ad9a4d0fe46a8d",
          "sha256": "3edda2d1d8221b93ff22774af0ae0a8c9e5b087735a354ebfefe87906c1867f2",
          "sha1": "ab4d7c55dacccb9c0844b753294de0ee7693ba44",
          "md5": "0a6920006855ddf8c49f6a08adac0256"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.17.0.aar",
          "url": "webkit-1.17.0.aar",
          "size": 292667,
          "sha512": "929d3a7425896f94cdbe2a561da5a4cd7cb2fdfb258ace2f0cc4a43bffcb35117db060e439baa97442fec1029f74c39d4f0c073778408e7cc9ad9a4d0fe46a8d",
          "sha256": "3edda2d1d8221b93ff22774af0ae0a8c9e5b087735a354ebfefe87906c1867f2",
          "sha1": "ab4d7c55dacccb9c0844b753294de0ee7693ba44",
          "md5": "0a6920006855ddf8c49f6a08adac0256"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "webkit-1.17.0-versionMetadata.json",
          "url": "webkit-1.17.0-versionMetadata.json",
          "size": 54619,
          "sha512": "ab87d38874cfcb400d5703c95c0c3d1173e22fc0938202d0717df58888ce968277647f39d26a88de170950eac3fb216c4c606f6968d24ab30f4f500c1b722543",
          "sha256": "bf3af9733aadfb24b96ee5a05aab76c4631eea60d906a3618a0f8acb79b8b6ed",
          "sha1": "66e82147f9db55c8d9e8a9aad2fe99cabed31b76",
          "md5": "c03215aee0beb93bae0ecd3a7186a706"
        }
      ]
    }
  ]
}