{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.3.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-2.3.21-all.jar",
          "url": "kotlin-test-2.3.21-all.jar",
          "size": 8870,
          "sha512": "b4dbb9c6f8be1e8050cafa89bdb7df682f1f3f3e4db3c4fbb9976df3eb05b6c4aa47b10383888eda6cd8d663e2913f1216a65ee64f0a0f3228bd9a62db75f1e9",
          "sha256": "51c1158027ab9663f8420cfcc8939b3aeb05407b9082fce7c2e3f2d7813ed2b4",
          "sha1": "55283bbd5f337c78e3290a17c3a6f5c0d3148097",
          "md5": "594c0dcadf9a737da6251b3aaace47dc"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "jvmApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-2.3.21.jar",
          "url": "kotlin-test-2.3.21.jar",
          "size": 102711,
          "sha512": "0e010cf854ec9deefa96d392756eef05f91cdd13b0e78291fa3d924e806f9eef272b57d58bfa644b9d9a104309afde0522fa952216dea3cf3909aa2a04f286f4",
          "sha256": "038f7d2c7df1039450809c486068f301a29c6e90356c9a4b595e34f4f4a813e7",
          "sha1": "8579caa50cab9f55a3a91658c2e4db914675352f",
          "md5": "94f37a693c37434104db079d907153f4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-2.3.21.jar",
          "url": "kotlin-test-2.3.21.jar",
          "size": 102711,
          "sha512": "0e010cf854ec9deefa96d392756eef05f91cdd13b0e78291fa3d924e806f9eef272b57d58bfa644b9d9a104309afde0522fa952216dea3cf3909aa2a04f286f4",
          "sha256": "038f7d2c7df1039450809c486068f301a29c6e90356c9a4b595e34f4f4a813e7",
          "sha1": "8579caa50cab9f55a3a91658c2e4db914675352f",
          "md5": "94f37a693c37434104db079d907153f4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-test-2.3.21-sources.jar",
          "url": "kotlin-test-2.3.21-sources.jar",
          "size": 12385,
          "sha512": "63bc8202a124550f21541d539956e2f6f44dcf8dc47e0867e237f86e3746f3182969334e594841632b984688dee98d4eaf35fd82d6368f4479666a6e7b5b6607",
          "sha256": "bce4ebcf90507cc14ea3857f65088d10fd1a305616da62a6e5b6be0735ccb456",
          "sha1": "2f3205c911113a3d06ac492ed0c84d6f30fbd069",
          "md5": "de3bcbf25fa5c7e5569ca4b262637c4d"
        }
      ]
    },
    {
      "name": "nativeApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.3.21"
          }
        }
      ]
    },
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-js/2.3.21/kotlin-test-js-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-js",
        "version": "2.3.21"
      }
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-js/2.3.21/kotlin-test-js-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-js",
        "version": "2.3.21"
      }
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-js/2.3.21/kotlin-test-js-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-js",
        "version": "2.3.21"
      }
    },
    {
      "name": "jvmJUnitApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit/2.3.21/kotlin-test-junit-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit",
        "version": "2.3.21"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "jvmJUnitRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit/2.3.21/kotlin-test-junit-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit",
        "version": "2.3.21"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "jvmJUnitSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit/2.3.21/kotlin-test-junit-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit",
        "version": "2.3.21"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "jvmJUnit5ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit5/2.3.21/kotlin-test-junit5-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit5",
        "version": "2.3.21"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "jvmJUnit5RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit5/2.3.21/kotlin-test-junit5-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit5",
        "version": "2.3.21"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "jvmJUnit5SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit5/2.3.21/kotlin-test-junit5-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit5",
        "version": "2.3.21"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "jvmTestNGApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-testng/2.3.21/kotlin-test-testng-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-testng",
        "version": "2.3.21"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "jvmTestNGRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-testng/2.3.21/kotlin-test-testng-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-testng",
        "version": "2.3.21"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "jvmTestNGSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-testng/2.3.21/kotlin-test-testng-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-testng",
        "version": "2.3.21"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.3.21"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.3.21"
        }
      ]
    },
    {
      "name": "wasmJsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-js/2.3.21/kotlin-test-wasm-js-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-js",
        "version": "2.3.21"
      }
    },
    {
      "name": "wasmJsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-js/2.3.21/kotlin-test-wasm-js-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-js",
        "version": "2.3.21"
      }
    },
    {
      "name": "wasmJsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-js/2.3.21/kotlin-test-wasm-js-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-js",
        "version": "2.3.21"
      }
    },
    {
      "name": "wasmWasiApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-wasi/2.3.21/kotlin-test-wasm-wasi-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-wasi",
        "version": "2.3.21"
      }
    },
    {
      "name": "wasmWasiRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-wasi/2.3.21/kotlin-test-wasm-wasi-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-wasi",
        "version": "2.3.21"
      }
    },
    {
      "name": "wasmWasiSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-wasi/2.3.21/kotlin-test-wasm-wasi-2.3.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-wasi",
        "version": "2.3.21"
      }
    }
  ]
}
