{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.logging.log4j",
    "module": "log4j-to-slf4j",
    "version": "2.25.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.25.5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "biz.aQute.bnd",
          "module": "biz.aQute.bnd.annotation",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.38.0"
          }
        },
        {
          "group": "org.osgi",
          "module": "org.osgi.annotation.bundle",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.osgi",
          "module": "org.osgi.annotation.versioning",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "log4j-to-slf4j-2.25.5.jar",
          "url": "log4j-to-slf4j-2.25.5.jar",
          "size": 24173,
          "sha512": "aba646c8b91906b118aa02dcebd56af56a957e9f0ec4dce8ae3c91e71ffb2fce0d047503c09f1cab665702405f67742e427277e00941e082d0239df2c82ef935",
          "sha256": "b68e8b47342dbc9b35644a14fe2efc0b7bf18da703910cd05ad5501ffe07bba1",
          "sha1": "bafb12d62913815e040218e34c80d75ad6db09c1",
          "md5": "9927bacbf08e748e4c816338658aeb7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.25.5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "log4j-to-slf4j-2.25.5.jar",
          "url": "log4j-to-slf4j-2.25.5.jar",
          "size": 24173,
          "sha512": "aba646c8b91906b118aa02dcebd56af56a957e9f0ec4dce8ae3c91e71ffb2fce0d047503c09f1cab665702405f67742e427277e00941e082d0239df2c82ef935",
          "sha256": "b68e8b47342dbc9b35644a14fe2efc0b7bf18da703910cd05ad5501ffe07bba1",
          "sha1": "bafb12d62913815e040218e34c80d75ad6db09c1",
          "md5": "9927bacbf08e748e4c816338658aeb7a"
        }
      ]
    }
  ]
}
