{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-1.7.0-multiplatform-sources.jar",
          "url": "foundation-layout-1.7.0-multiplatform-sources.jar",
          "size": 98499,
          "sha512": "16202ee48023d12a65735d3f386dab34a8d9a84f9f2a57f3aa61d5ed6682d46424b40bb8d0cb897c443d3a56920180e7de6f46f358febb16b2a2cc1ad4b1c3f6",
          "sha256": "812a454b3e455198c5cb5610d7e6a8af1d96e4962c4f212b31b53b81095813f0",
          "sha1": "6d0afe6e2276e588db0ca643cbdcea1c365b65f3",
          "md5": "17ab013b9e7aea2e3b90172b34327443"
        },
        {
          "name": "foundation-layout-1.7.0-samples-sources.jar",
          "url": "foundation-layout-1.7.0-samples-sources.jar",
          "size": 26643,
          "sha512": "beb80b648aa2e4d43ba2c7e2d0a5cbf39846f6063620f94f0d4be4b738c9a92086b4d7345bade4466d52a329d3d7c4c9117abb11b80dfafebdf58264aad4538f",
          "sha256": "d5cdba46a265c956ea9026ccc9d100f133ca39836fad6d61f897cb2173f91306",
          "sha1": "c30fcc13ba6e6f10f524c3e5b3fee1f92ead2616",
          "md5": "344cf5e95eb6c8ee9077a1ac7bbd6dfe"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "foundation-layout-1.7.0-versionMetadata.json",
          "size": 29819,
          "sha512": "eaafbfb0bcb63075332ff769f65935ff89ae4dcec338a835014d06399d6cebbb6598839350bd6860491ab42e7bd97d5aaf00bbf4cd456b5959557725966a24ac",
          "sha256": "f6c0dfee352d82b57c888017a69db21514cfdea8e311ea74012b738681a0f19b",
          "sha1": "e4be5fb94e9706fa41d57d2f1f84d354db29ae9b",
          "md5": "64285e2607ffda8375181f7fb2bf363a"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-metadata-1.7.0.jar",
          "url": "foundation-layout-1.7.0.jar",
          "size": 711,
          "sha512": "c976f2741d710817f385c8a7df959e5a09b90426f82e4fb37d1025e0404e4013c68e13fcbccfbdb93975348e779ea038589c46455f9af9615904bab3b93f824d",
          "sha256": "4e75469751c9d4c464c7d06af283b9737693c20bc4aaf657630bb294c27bbff1",
          "sha1": "2ac53dae14bbb0b6ccb809713e8cf9d1dec92bee",
          "md5": "35c88048156fb6fdb2fa56444ffd0c2d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-kotlin-1.7.0-sources.jar",
          "url": "foundation-layout-1.7.0-sources.jar",
          "size": 79858,
          "sha512": "3f7fb984ab206fd30143e2886fe39dfe2a33f4e3da5cf9d1ab5a375e6fd1d89c80f9ef7a97877ea87ae73cad7c71c211521bb244aa7082406c5dbd271a56a5b8",
          "sha256": "c4f90dab22f0392f9263e8018bef96e2d802675fcbdc140718c7a3213ed1a718",
          "sha1": "0d8b014ceb45776cb1e442126fb2880485a5bdce",
          "md5": "c55907bbfa6d02ccb822db9cbb432b44"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.7.0/foundation-layout-android-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.7.0/foundation-layout-android-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.7.0/foundation-layout-android-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-desktop/1.7.0/foundation-layout-desktop-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-desktop/1.7.0/foundation-layout-desktop-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-desktop/1.7.0/foundation-layout-desktop-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-desktop",
        "version": "1.7.0"
      }
    }
  ]
}