{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-1.7.0-multiplatform-sources.jar",
          "url": "animation-core-1.7.0-multiplatform-sources.jar",
          "size": 108290,
          "sha512": "cc4a684080eedca1562e7a37830c71170fae3242132fa2adf1cd9523372fd12cb1c6899290e159cf8f0ec6767762fbffadb2d91b06c7708e859a03c9df9bfb15",
          "sha256": "7eae0773650180fd95b27f3dd92f4f0107b670651e4326fbc9303d63a288ead0",
          "sha1": "1a35a4f0da8bff6c0f4648721f0922160b7df0e8",
          "md5": "826c5e76353e85b3efb8e37845797790"
        },
        {
          "name": "animation-core-1.7.0-samples-sources.jar",
          "url": "animation-core-1.7.0-samples-sources.jar",
          "size": 21581,
          "sha512": "3c73a3f0c32384a73249261ee144869051216142873d613bbb81ef9571234569989e8a47b46e89923e2cff99e3168a2b84d116bab4d6c4e857cf5e31d641b3d5",
          "sha256": "65f285737261e025985d4582f6093693c4c731bceb2c84c97ed74874304c5181",
          "sha1": "5f4e9009e638c425f3613758eed8fed58bb44a23",
          "md5": "b316a9acf946ab6ec27c63b870eda9c3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "animation-core-1.7.0-versionMetadata.json",
          "size": 52126,
          "sha512": "e2c8f2755123a353d106744e43bc909f88d17e730485dc08c6c4025184995bfedf5a002821021b8e0df631ee9936666c6c0ce00bb4c25df9841c9b0c20f4d99d",
          "sha256": "c9933eaa3683022d05b473fe61343d5f8b9083c8d785bab1b68a6cd54c3d68b1",
          "sha1": "021763c45021ad7d21cb2f21ab07e50a908b1838",
          "md5": "9accbd82e44938fbf18308e78591e298"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-metadata-1.7.0.jar",
          "url": "animation-core-1.7.0.jar",
          "size": 723,
          "sha512": "d6bf93025b5e97ca042ed0a622a7c735c40d03bcd8113a2c2e4463cd42f2a90da92694e681f9f3c7f363012f18fcaf583dfb81d7739efe5a2cb20671e8091417",
          "sha256": "b628671c9ebefd68ff33b35d2c5ca644bdb4f110c5fa24260930258d4bfef93d",
          "sha1": "53af16e46e0bd030589b6c7d085f3dbac8fca1a6",
          "md5": "bab5e2d76e88be349e872e63db91d1c2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-kotlin-1.7.0-sources.jar",
          "url": "animation-core-1.7.0-sources.jar",
          "size": 107966,
          "sha512": "612aab9101d827e333d136ac12789279f41357527cf30c265219983d76f7110e8f97adceb323371b8d07e1536436e58a2e5523f8bfd62bb6a666c15aaeffd045",
          "sha256": "951ae345b2641da83549fb0c6a45651e1a55d73d7f89e77ce938beb56a2d40a2",
          "sha1": "af99d9f325065686f9f68a2abff1d9c712eb7f50",
          "md5": "276167c41908daac5a692b356fe12929"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../animation-core-android/1.7.0/animation-core-android-1.7.0.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../animation-core-android/1.7.0/animation-core-android-1.7.0.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../animation-core-android/1.7.0/animation-core-android-1.7.0.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-core-desktop/1.7.0/animation-core-desktop-1.7.0.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-core-desktop/1.7.0/animation-core-desktop-1.7.0.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-core-desktop/1.7.0/animation-core-desktop-1.7.0.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-desktop",
        "version": "1.7.0"
      }
    }
  ]
}