{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.1.1.jar",
          "url": "spring-boot-gradle-plugin-4.1.1.jar",
          "size": 156289,
          "sha512": "99daab00b348058f483ec0ac953e88a9a4f146beb56e0d2106b9c72a9537709c2963a0c97b6af6d1ec808d49032cbc47e0631b825be398a71e4f11ee438e5fea",
          "sha256": "1e9b7a39bb0c24f15c860f6d444a5ab5a207d40c62f19d71cfb95fc819ccf2f2",
          "sha1": "8cf93ecefab5b097f842e5128cece5c866a7c19b",
          "md5": "1f45726dcb1dea9f48f2dd508ed6b2a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.1.1.jar",
          "url": "spring-boot-gradle-plugin-4.1.1.jar",
          "size": 156289,
          "sha512": "99daab00b348058f483ec0ac953e88a9a4f146beb56e0d2106b9c72a9537709c2963a0c97b6af6d1ec808d49032cbc47e0631b825be398a71e4f11ee438e5fea",
          "sha256": "1e9b7a39bb0c24f15c860f6d444a5ab5a207d40c62f19d71cfb95fc819ccf2f2",
          "sha1": "8cf93ecefab5b097f842e5128cece5c866a7c19b",
          "md5": "1f45726dcb1dea9f48f2dd508ed6b2a4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.1.1-javadoc.jar",
          "url": "spring-boot-gradle-plugin-4.1.1-javadoc.jar",
          "size": 348449,
          "sha512": "602166e0a1daacc2f133547da563ad8916c38345f2ab8dc5ba8798168c8bfe0a1d98c06aa57cf6a62363bde6f0f1fd056b13ff3bb32e48b06e275058eed03c55",
          "sha256": "84ba00a792a6aecbac536e0f290a80739c8a266a752d2c024c3cdc89eb8da778",
          "sha1": "0cd18e1ca3679149b508fdcb2150042870a43c85",
          "md5": "9806848ab3dbcbaa456e9320f604cec3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.1.1-sources.jar",
          "url": "spring-boot-gradle-plugin-4.1.1-sources.jar",
          "size": 84774,
          "sha512": "6dbc591b830e98dc5c99851c29e4ec4b060f93cda9a42d7e6d3b657e7d22a5afaf28327b5d2a30ed04b9c512a4a6835db551bc67df5de5d991e8ec1bec5f9132",
          "sha256": "237a26b55f7109874bbe44896f1ed9cc6e60db59c436e7c0ffa525188febe1e0",
          "sha1": "829a238c3261706b67e544f292d7d3909400dd27",
          "md5": "70eb8a77b477e6d48e56cb80c933a048"
        }
      ]
    }
  ]
}
