{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-1.7.0-multiplatform-sources.jar",
          "url": "ui-tooling-preview-1.7.0-multiplatform-sources.jar",
          "size": 13525,
          "sha512": "d23df38b355f3803cb4ee552c423b17ab035f6de7dba1d223dfab3acfdcb5fd5d4c2d25d3c95f63e84154b13c679996f084c18e55af1458847f0a24af289fdae",
          "sha256": "25513d9ec8a2c3109163bd95a2bd4ac6b3248a61e00b6f58d2ad1eca66b999d9",
          "sha1": "1b43c967e15486e1d5812194385dbd3bf82f3b6c",
          "md5": "3425dada5afbd7504b75dfed7f667839"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-tooling-preview-1.7.0-versionMetadata.json",
          "size": 4827,
          "sha512": "0c16af5bb9c7f7abda26974748dd7fa2140c734bfceeb76fe7c818e53b970e5595400c68b2dbbf01758585f0d29df21bcfafc1484aeee7f2478ed842fe2a5f60",
          "sha256": "c0577b04a2464bf7dbf8bf13944fdb781d3bfe81adbd6338225c02a6e649eefd",
          "sha1": "964c3cb3575499d248f954a30e7b11a9978a879e",
          "md5": "7c0b4bc3fddcb7fd5fc277f831d62548"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-metadata-1.7.0.jar",
          "url": "ui-tooling-preview-1.7.0.jar",
          "size": 724,
          "sha512": "315eae76dc234056f4e4030e2507a8b83c03e2c768aa05758d22103883b9a749fce91dd49f2f3179fc08282609043b549472da97e3493e8311bbe9559d337415",
          "sha256": "9328484158a30fbb2ebe5693605700ae9c4ad61af2fad531464561c09a4f3653",
          "sha1": "3e40bfcebe59f3e98fa919b978cf15214bb889c3",
          "md5": "5f0f9fb3d686f339fb630d78d9ff7594"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-kotlin-1.7.0-sources.jar",
          "url": "ui-tooling-preview-1.7.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-tooling-preview-android/1.7.0/ui-tooling-preview-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-preview-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-tooling-preview-android/1.7.0/ui-tooling-preview-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-preview-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-tooling-preview-android/1.7.0/ui-tooling-preview-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-preview-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-tooling-preview-desktop/1.7.0/ui-tooling-preview-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-preview-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-tooling-preview-desktop/1.7.0/ui-tooling-preview-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-preview-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-tooling-preview-desktop/1.7.0/ui-tooling-preview-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-preview-desktop",
        "version": "1.7.0"
      }
    }
  ]
}