{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-geometry",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-geometry-1.7.0-multiplatform-sources.jar",
          "url": "ui-geometry-1.7.0-multiplatform-sources.jar",
          "size": 20598,
          "sha512": "8179dbe698d86ff0afb7f1c855c06ddd88df60bfd6b55486353df44c11297744f0cd9c563c52345621f8f10eb92966a9788ef9add5b018ceae053e0e8473a4d3",
          "sha256": "7c0b74d59159991c524cd710c013e6ab157fa3b67f1712869ab766fbed0a828a",
          "sha1": "324e8553492ae16b3e7282183c48c4f701c6c2c4",
          "md5": "ad963444e93343de0d0b3f5a4a0d110f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-geometry-1.7.0-versionMetadata.json",
          "size": 10286,
          "sha512": "9f389b900ee16dc446ad6fc47b1f6a0124236f2be972a82f81a060d79547fa2f01da9fe38e2508e0c66fd29bb654ebbbdbb67c5a5e6dcfae7466614345cccd69",
          "sha256": "bd81f19dbfccc500c1f47771a146a73cb95269623a6d366c423d0a436356f542",
          "sha1": "f0e57e4432f00113d74da4dd67b9f53cb7cdf6be",
          "md5": "231fdbac7b18403bde325d900d5dfbc1"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-geometry-metadata-1.7.0.jar",
          "url": "ui-geometry-1.7.0.jar",
          "size": 686,
          "sha512": "3670896f9db064a294104884c88b87c16a74bda01b7d4a27a9a57e66098e0ecaafc2df156b820030fc3b03a8d1600116006377fd3efc0f5ee41a1aefd784545e",
          "sha256": "00421ed4ed83f8b1ef2a22434a6c7102bb08e16b2cc4acfda503da9ddc213e91",
          "sha1": "62eb93f6962892bbee14e30bae1deef051d38845",
          "md5": "2569cf553a2f2e71a0c5ea1c5d7a87e2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-geometry is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-geometry-kotlin-1.7.0-sources.jar",
          "url": "ui-geometry-1.7.0-sources.jar",
          "size": 20272,
          "sha512": "6b6398da495a8ca4220a00f550003feaeaed5cc3f5281a2b1750ecd003c71db15376f1030343df4b1b0811527f70c37afa78850751132bf677428a11f6e20f3a",
          "sha256": "9771e9108e33a3180d8ba84e1d54d17e3b3d5e3249528f1ed5759c7bd86247ec",
          "sha1": "01dd31c0c8b7e1d3d94f2d3811e82ac96feca355",
          "md5": "eed40aa2c524ff82c48149c05ba9b194"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-geometry-android/1.7.0/ui-geometry-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-geometry-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-geometry-android/1.7.0/ui-geometry-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-geometry-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-geometry-android/1.7.0/ui-geometry-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-geometry-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-geometry-desktop/1.7.0/ui-geometry-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-geometry-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-geometry-desktop/1.7.0/ui-geometry-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-geometry-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-geometry-desktop/1.7.0/ui-geometry-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-geometry-desktop",
        "version": "1.7.0"
      }
    }
  ]
}