{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/1.4.0/savedstate-1.4.0.module",
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14329657"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate.aar",
          "url": "savedstate-android-1.4.0.aar",
          "size": 136412,
          "sha512": "848bd45a9017e2ecfdd002faa6264fdab491e65c5d532513e5fcfb4808cd12e2b9704f8b14ffc18bb11d5577731f35151e177358216676702b2f31e3b8eb074c",
          "sha256": "1656ce62cd233d488bdbbd42e533b80b22435b7a690acae6dbe7302392512c14",
          "sha1": "8cf8663a8d810d4d50110ff135b3cd1d7227c867",
          "md5": "a92dbdc46006ac0bccbb1edda5bccaef"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "prevents symbols duplication"
        }
      ],
      "files": [
        {
          "name": "savedstate.aar",
          "url": "savedstate-android-1.4.0.aar",
          "size": 136412,
          "sha512": "848bd45a9017e2ecfdd002faa6264fdab491e65c5d532513e5fcfb4808cd12e2b9704f8b14ffc18bb11d5577731f35151e177358216676702b2f31e3b8eb074c",
          "sha256": "1656ce62cd233d488bdbbd42e533b80b22435b7a690acae6dbe7302392512c14",
          "sha1": "8cf8663a8d810d4d50110ff135b3cd1d7227c867",
          "md5": "a92dbdc46006ac0bccbb1edda5bccaef"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-android-1.4.0-sources.jar",
          "url": "savedstate-android-1.4.0-sources.jar",
          "size": 57475,
          "sha512": "0d91b7d3a022a47e8a521b126ad0dd003598f502392deaf29c10c6143617b5546a71d07ebb23d4c773731fddc9161dea71657eb47da3e34ccbb156e1ebfc591a",
          "sha256": "ab5ddfcea3cf8507428183cac36144629aa9a5cd8631afdfbb762e844c8785d9",
          "sha1": "fddb1b8f7f11f495560f3fb75088a4e5814411db",
          "md5": "55818ade30bcfcf529bd01a356133f00"
        },
        {
          "name": "savedstate-1.4.0-samples-sources.jar",
          "url": "savedstate-android-1.4.0-samples-sources.jar",
          "size": 7330,
          "sha512": "f1b77905da38cc98f6efcd3f9a440b2f2e91887e64fa966f707f4613163bbbc5893f32d235b4a5e6ecea3847264af93f898d4585eee2d1f4558ed0c0545de34d",
          "sha256": "55d183dec7a7b59cfc754f1fde95262298a33ae1abc9a2554d7640ee1360ee1e",
          "sha1": "45540714f2e54e94c96da6214912c134ffcd9d32",
          "md5": "6cf2c87e40e1ebafa911b4df0300f2cb"
        }
      ]
    }
  ]
}