{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.2.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-2.2.20-all.jar",
          "url": "kotlin-test-2.2.20-all.jar",
          "size": 8738,
          "sha512": "92b1d6abd3e61fe76372fab16c402d471a741513ef223ac9c8aa93d59e0dc18c09d36f5b1e640e595bd3d01e0989643d8edcb85942f5c35aabb69eb87b7877db",
          "sha256": "b681fa192b6c62b03c69b0a73f81deb1daf2191cfc0ce8925444932f548d38b4",
          "sha1": "36def1aba0ffe9e5ded31593bb4744dba7a3ad00",
          "md5": "23c44e2f44c2e8561abc1df3850323a4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "jvmApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-2.2.20.jar",
          "url": "kotlin-test-2.2.20.jar",
          "size": 102394,
          "sha512": "1143ae4295968c0909a911407dce981b86376177719580f8311b80c51430f619761be6a55d37200db539f94bdb9605ab98d7da3e6035fd00dc3dac87e3554c5a",
          "sha256": "0054c51c672512a918440703e35ea946a8e7a210872f2196dbd6b9f2959198b0",
          "sha1": "00e8b447088d8f3cfd945177f307ec7ee524fb96",
          "md5": "5c9f43739ffce9bc08ceba5142e325c8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-2.2.20.jar",
          "url": "kotlin-test-2.2.20.jar",
          "size": 102394,
          "sha512": "1143ae4295968c0909a911407dce981b86376177719580f8311b80c51430f619761be6a55d37200db539f94bdb9605ab98d7da3e6035fd00dc3dac87e3554c5a",
          "sha256": "0054c51c672512a918440703e35ea946a8e7a210872f2196dbd6b9f2959198b0",
          "sha1": "00e8b447088d8f3cfd945177f307ec7ee524fb96",
          "md5": "5c9f43739ffce9bc08ceba5142e325c8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-test-2.2.20-sources.jar",
          "url": "kotlin-test-2.2.20-sources.jar",
          "size": 11672,
          "sha512": "456c65c7a6917d20d88341d4f4f467ff065848914f727c7d63d4fe019e9020231272b05cf766ac5ba727d3f723e197728f23d6d4ecc02d0b94e1e2189c02c088",
          "sha256": "c8445545032c2e09195fc883b274260dd414b33f2cdc1dadd4f3441c1a4e456b",
          "sha1": "002b21ba5a30a7a6eb2f5fea532122bf9b5dda05",
          "md5": "a8fc3f5fe5e6b4614b4b532d6803fad0"
        }
      ]
    },
    {
      "name": "nativeApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.2.20"
          }
        }
      ]
    },
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-js/2.2.20/kotlin-test-js-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-js",
        "version": "2.2.20"
      }
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-js/2.2.20/kotlin-test-js-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-js",
        "version": "2.2.20"
      }
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-js/2.2.20/kotlin-test-js-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-js",
        "version": "2.2.20"
      }
    },
    {
      "name": "jvmJUnitApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit/2.2.20/kotlin-test-junit-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit",
        "version": "2.2.20"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "jvmJUnitRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit/2.2.20/kotlin-test-junit-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit",
        "version": "2.2.20"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "jvmJUnitSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit/2.2.20/kotlin-test-junit-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit",
        "version": "2.2.20"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "jvmJUnit5ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit5/2.2.20/kotlin-test-junit5-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit5",
        "version": "2.2.20"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "jvmJUnit5RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit5/2.2.20/kotlin-test-junit5-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit5",
        "version": "2.2.20"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "jvmJUnit5SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit5/2.2.20/kotlin-test-junit5-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit5",
        "version": "2.2.20"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "jvmTestNGApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-testng/2.2.20/kotlin-test-testng-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-testng",
        "version": "2.2.20"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "jvmTestNGRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-testng/2.2.20/kotlin-test-testng-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-testng",
        "version": "2.2.20"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "jvmTestNGSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-testng/2.2.20/kotlin-test-testng-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-testng",
        "version": "2.2.20"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.2.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "wasmJsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-js/2.2.20/kotlin-test-wasm-js-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-js",
        "version": "2.2.20"
      }
    },
    {
      "name": "wasmJsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-js/2.2.20/kotlin-test-wasm-js-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-js",
        "version": "2.2.20"
      }
    },
    {
      "name": "wasmJsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-js/2.2.20/kotlin-test-wasm-js-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-js",
        "version": "2.2.20"
      }
    },
    {
      "name": "wasmWasiApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-wasi/2.2.20/kotlin-test-wasm-wasi-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-wasi",
        "version": "2.2.20"
      }
    },
    {
      "name": "wasmWasiRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-wasi/2.2.20/kotlin-test-wasm-wasi-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-wasi",
        "version": "2.2.20"
      }
    },
    {
      "name": "wasmWasiSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-wasi/2.2.20/kotlin-test-wasm-wasi-2.2.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-wasi",
        "version": "2.2.20"
      }
    }
  ]
}
