{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-bom",
    "version": "2025.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.7"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-test",
          "version": {
            "requires": "3.8.7"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-tools",
          "version": {
            "requires": "3.8.7"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core-micrometer",
          "version": {
            "requires": "3.8.7"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-extra",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-adapter",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-core",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http-brave",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-quic",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-pool",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-pool-micrometer",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions",
          "version": {
            "requires": "1.3.2"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.7"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-test",
          "version": {
            "requires": "3.8.7"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-tools",
          "version": {
            "requires": "3.8.7"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core-micrometer",
          "version": {
            "requires": "3.8.7"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-extra",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-adapter",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-core",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http-brave",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-quic",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-pool",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-pool-micrometer",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions",
          "version": {
            "requires": "1.3.2"
          }
        }
      ]
    }
  ]
}
