{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-4.1.1.jar",
          "url": "spring-boot-buildpack-platform-4.1.1.jar",
          "size": 332940,
          "sha512": "85820b86b909a3b06717872ba2ec876e1c220aaafefd55dccd569095e592b2183037a21acf65160e2ffc731a55e46c7b0c761202c627903a7b9506853a9dc480",
          "sha256": "732e099296492e24b60894553dab8349da84dc2f02c84322ac3e6eadb7968539",
          "sha1": "959f096fe85e8167d91b5cc963077cfbd4548169",
          "md5": "1c071d59e1ae84604f67efa0d6aac1d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.6.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.9"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-4.1.1.jar",
          "url": "spring-boot-buildpack-platform-4.1.1.jar",
          "size": 332940,
          "sha512": "85820b86b909a3b06717872ba2ec876e1c220aaafefd55dccd569095e592b2183037a21acf65160e2ffc731a55e46c7b0c761202c627903a7b9506853a9dc480",
          "sha256": "732e099296492e24b60894553dab8349da84dc2f02c84322ac3e6eadb7968539",
          "sha1": "959f096fe85e8167d91b5cc963077cfbd4548169",
          "md5": "1c071d59e1ae84604f67efa0d6aac1d3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-4.1.1-javadoc.jar",
          "url": "spring-boot-buildpack-platform-4.1.1-javadoc.jar",
          "size": 486102,
          "sha512": "9d6aeacc24425584d3a958dea24abb2ba533d41a7b5bafb68c58e2a8f016dd8e21b4e9510ad3c0e3341730c0aa914914d5718d660b8aec8466ad2681690ebdaf",
          "sha256": "e9e3329d06bcf106acf6a4687162ad0f512d589ff714adf8a8467f02a825ed99",
          "sha1": "bc4b25b9ce57243b97e9cd88b746ae7553e4cdfe",
          "md5": "e8f0ccc64b592996538c7ec4f1c8c8ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-4.1.1-sources.jar",
          "url": "spring-boot-buildpack-platform-4.1.1-sources.jar",
          "size": 194440,
          "sha512": "9a34a8f7be47073827c7976a34a7d970bff854b378fe815f7226ecf6ff783f764db33e68d78b408e580af61cc42972e55d53d838a6cf1e3bce2611b5e72c99ba",
          "sha256": "38729fe5de90e2f04a227153a5f55a2daf2f5e498ea7dea909144382042e39e0",
          "sha1": "7df0461e25beb623afef940809c0a9781d10a3ab",
          "md5": "f89cf882ff0a2fcb487d4b3663840644"
        }
      ]
    }
  ]
}
