{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "14122761"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-metadata-1.9.2.jar",
          "url": "animation-core-1.9.2.jar",
          "size": 47686,
          "sha512": "88bf65b0c83c87900bae9425bb0214ab3fb1c2834c6dc4bcffe471e4467e715b701df7dadafbb4cbfdf8d54612902332b9df886834bfa951c64f413658c8b931",
          "sha256": "61ff5030fa00a03824ddc18797a9a152786f2c4d0734e4d3ebf4108a2581e86a",
          "sha1": "25280e2f18749cfdcfd46d0ca77acad596ba5890",
          "md5": "cb2bdab73a8f712c3f4ea55a329713b2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-kotlin-1.9.2-sources.jar",
          "url": "animation-core-1.9.2-sources.jar",
          "size": 115955,
          "sha512": "dd2e998bfd8a23dc670c84ce9419686e7bea00d86db5ff1200acd62e90bccc258f4931078d1dc1fe19922ba098ecada4592f758a0028edd4c3db4ae100f32e47",
          "sha256": "867810214caec50f3ef65a3ea83ecc24823ee692c3e91e17cc97b1b90be9dfe8",
          "sha1": "12ac4d58ddf5a623111b3f92075714a9bbd3454f",
          "md5": "e608a0939d9f3d5df47aba93fe0a442c"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-1.9.2-multiplatform-sources.jar",
          "url": "animation-core-1.9.2-multiplatform-sources.jar",
          "size": 115312,
          "sha512": "a8407648196c30467ab1012a9b192b4611a37074a5aa0e4a448b29de8524ff44e1d0bd6099ce963898cd9354324a22924d2b94edaae123850df9480448401165",
          "sha256": "13c01425415b08c29c168e72b283db01ce265469e721e06de3948360c44e09bb",
          "sha1": "afdf049bfc6c75d15ee1ffe3df5f7cae7d80fd44",
          "md5": "aaf0ba52b87233276cdaacfe71690ac1"
        },
        {
          "name": "animation-core-1.9.2-samples-sources.jar",
          "url": "animation-core-1.9.2-samples-sources.jar",
          "size": 25951,
          "sha512": "c47d7caa2fa6ea92a57a886adecc37494bae8712706a45067ac3c1eed8dc599c9cfc258959cb4e73c3c00309f49a6867347f7f39f9a71fde8028324df6353ddf",
          "sha256": "cbd4b9814d7e2af91b3a22f554e75281beaf23c3f47016f98a79b1ac0f3cb6b2",
          "sha1": "ae139cc0ab318b5bb8cf986e43f25356bfc126c8",
          "md5": "a46005f614a432aa11f427df6ba5e618"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "animation-core-1.9.2-versionMetadata.json",
          "size": 61062,
          "sha512": "89fdc3f4af808defdf72d3539e1e1f9be03a97b9a256163cdee25329f24b853eea44e66fc05308de6de31c11ce1a4e9ecb24e7214a1b8625866ad5348378238d",
          "sha256": "2d830fba21e6ad79b7ea634908e42d0af7e7c0ed6eb1f06494808ed24bc69e76",
          "sha1": "3555fe680a1e1c7ef983ff4a0844d10e3486ef28",
          "md5": "a913669a5df3df1ff5650ee1c73fd84c"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-core-android/1.9.2/animation-core-android-1.9.2.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-android",
        "version": "1.9.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-core-android/1.9.2/animation-core-android-1.9.2.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-android",
        "version": "1.9.2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-core-android/1.9.2/animation-core-android-1.9.2.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-android",
        "version": "1.9.2"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-core-jvmstubs/1.9.2/animation-core-jvmstubs-1.9.2.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-jvmstubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-core-jvmstubs/1.9.2/animation-core-jvmstubs-1.9.2.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-jvmstubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-core-jvmstubs/1.9.2/animation-core-jvmstubs-1.9.2.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-jvmstubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../animation-core-linuxx64stubs/1.9.2/animation-core-linuxx64stubs-1.9.2.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-linuxx64stubs",
        "version": "1.9.2"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../animation-core-linuxx64stubs/1.9.2/animation-core-linuxx64stubs-1.9.2.module",
        "group": "androidx.compose.animation",
        "module": "animation-core-linuxx64stubs",
        "version": "1.9.2"
      }
    }
  ]
}