{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-util/1.9.2/ui-util-1.9.2.module",
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "14122761"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util.aar",
          "url": "ui-util-android-1.9.2.aar",
          "size": 22837,
          "sha512": "39767565c4bd4d492e089f47e9179c1c321e7368f82d950657f2496fa488b3c95b8e5d35c7ebe8297f22e43cef56baa09a74c7e9281925e96a81fedfcbeaaee7",
          "sha256": "e1770640c59a0e2867a2e7fa4ce55cabd81362de6023ddc8e87982d9ba496e9e",
          "sha1": "8d702df49fb4aff1b7c1fd98d0caeb9843a9d5ff",
          "md5": "512eb9aa3f275a2069623d306d683b1f"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util.aar",
          "url": "ui-util-android-1.9.2.aar",
          "size": 22837,
          "sha512": "39767565c4bd4d492e089f47e9179c1c321e7368f82d950657f2496fa488b3c95b8e5d35c7ebe8297f22e43cef56baa09a74c7e9281925e96a81fedfcbeaaee7",
          "sha256": "e1770640c59a0e2867a2e7fa4ce55cabd81362de6023ddc8e87982d9ba496e9e",
          "sha1": "8d702df49fb4aff1b7c1fd98d0caeb9843a9d5ff",
          "md5": "512eb9aa3f275a2069623d306d683b1f"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-android-1.9.2-sources.jar",
          "url": "ui-util-android-1.9.2-sources.jar",
          "size": 19697,
          "sha512": "13ed2fe21bb99e68d084165e47a129030e8f92f708fe9cd87d68fa68b3c2c8f610473fd0eb45b85c50663ae1b5cc60fe48d99a27230809b253d63bc29ce28b8a",
          "sha256": "8a3779a18972952ce0834057c39bbe75c4d703c3a334fb687bc0fce81ab6b892",
          "sha1": "e5e5851e7762b57052cf0a290d6e286ee7296b45",
          "md5": "c866fed08181f9549258f90a0efb0df8"
        }
      ]
    }
  ]
}