{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-reactor-netty",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.1.1.jar",
          "url": "spring-boot-reactor-netty-4.1.1.jar",
          "size": 42736,
          "sha512": "2dc286de8e68948e7e0463fde14f055ec07b4c1d62844fde7d7b5f9ace526078baea7928bdecce248a4c6a65d880d36e3664168f40cfa7fb2314b1f71cb962a9",
          "sha256": "6ee3cacbb619e82a3230ef98ad95c661286af4c99aede4d3c37bc8bebbba20ae",
          "sha1": "b81ccae38636e1f66d3dc3ce814b71b33a95e82e",
          "md5": "fbf0e633334c2e051ab08cab778d3770"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-netty",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.1.1.jar",
          "url": "spring-boot-reactor-netty-4.1.1.jar",
          "size": 42736,
          "sha512": "2dc286de8e68948e7e0463fde14f055ec07b4c1d62844fde7d7b5f9ace526078baea7928bdecce248a4c6a65d880d36e3664168f40cfa7fb2314b1f71cb962a9",
          "sha256": "6ee3cacbb619e82a3230ef98ad95c661286af4c99aede4d3c37bc8bebbba20ae",
          "sha1": "b81ccae38636e1f66d3dc3ce814b71b33a95e82e",
          "md5": "fbf0e633334c2e051ab08cab778d3770"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.1.1-javadoc.jar",
          "url": "spring-boot-reactor-netty-4.1.1-javadoc.jar",
          "size": 152885,
          "sha512": "f5a9720b5ba68ef343a5e4545a3cef61db32c97074d419bd3ff85b846b5038d3f72a57e13589d16344ee9ef248bc67642013a01bf4e35500a95ae8037a0a1a1d",
          "sha256": "ff847f5ea33ca2e85772ac9edcc011edd72d9bd1626ac56c2083758941e2ed5a",
          "sha1": "32817890570ad5dd3a837dd83d4162f6db1f63ec",
          "md5": "54c95655afa25d0cb71056e447d691b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.1.1-sources.jar",
          "url": "spring-boot-reactor-netty-4.1.1-sources.jar",
          "size": 31435,
          "sha512": "20d4ecb2b26cc3a4fa548c7177b7e42d6117bad12a6400c5a68148f8a322a295860973613597b35cec64b4383d826354375e1abd88cea3ac081f484c13855d7a",
          "sha256": "6df9559bcc90df256894e02af8039ef92a50da413af3c58ad9d459898ab78cbf",
          "sha1": "5d5b458a99ccb56cbf0a07c73338da9a3e33d25c",
          "md5": "b87812b17967d5ecf6c675132b00ad80"
        }
      ]
    }
  ]
}
