{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-1.7.0-multiplatform-sources.jar",
          "url": "foundation-1.7.0-multiplatform-sources.jar",
          "size": 924181,
          "sha512": "7c2623bee0de4336336efec4d9614e3b991ef49521fdae3315cf470c9b848051d650ac7d2671052389b781b0655840069acfbd8accf129efe2a68a6a6b82685f",
          "sha256": "f9be1d4b29397176d4f622a5df9f83666a6e77cce0fd02033dada17f0a9c938f",
          "sha1": "3fcfeff2352aa9290053613adf85309a2172c13b",
          "md5": "655ad2c5bd19e677929e40a58a5187dc"
        },
        {
          "name": "foundation-1.7.0-samples-sources.jar",
          "url": "foundation-1.7.0-samples-sources.jar",
          "size": 70960,
          "sha512": "e6915fda8c84b27f1fb4ef88ad8fecf0946b6bb5ed172c17baeec6ea1c7f178203f3e8877e6fe31c05f4b48ae924697aa34fce3e48971495e938535a707372ad",
          "sha256": "5a6b849641c2a695f3a0581b3c0580ea75330660c32a6fd60ebaf475fdfc7b3f",
          "sha1": "73cc34ad1d4dc4fd23d3af615e71abf6880c7510",
          "md5": "644d279dff3106b5f276edd15a0ec1f1"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "foundation-1.7.0-versionMetadata.json",
          "size": 181283,
          "sha512": "5d5b9a1e3041ed04b386d9de87f0e7e1d14807e8f312cf372531c550f009e2ab3f5e1f89282f84f84aba1fdd2a6bbdb899414c3c740ebd9a10d05d2098d2e1a5",
          "sha256": "9196e8971e02b165b9bab71f1ccbdc11e782ece9ab920af261d9542521a6e6f8",
          "sha1": "318c0594bfe124cb6a19382fdf8edd1a61e7c5af",
          "md5": "fa78aba89250da2cd6c268735c26d887"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-metadata-1.7.0.jar",
          "url": "foundation-1.7.0.jar",
          "size": 744,
          "sha512": "641669d68fd9c81cbf406435bdb19a9b404b2576a2a84cbb130f14420a9189f91af2a64f1c3046bab297bfa45038b80956ff6477963a960081b84c14feaa8586",
          "sha256": "548f57ae3f6aa9ec87aaac82572f225f99830ec1ece01b622721947c8fb3075d",
          "sha1": "127b46f513500b442bf671026552f81c1c3ccf89",
          "md5": "ca851f221fa1a846318958893c07c55f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-kotlin-1.7.0-sources.jar",
          "url": "foundation-1.7.0-sources.jar",
          "size": 740059,
          "sha512": "29a21a82e8033eb53deeecd3c6880afa4035607d02039d5f75c8e6eac5a4a4844ba49ac2607136a2a9b6ce94c6642119586899c8cf4b53eb161e98401a6ecacd",
          "sha256": "cc2cb75020e48a27349d92790234f2ded5a2b71964a901ac125e9146a942a3ea",
          "sha1": "378cf193fb135e8449823e8ea2555c49017f0f1f",
          "md5": "e04978eee8357eb4d7204990b16a4f0d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.7.0/foundation-android-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.7.0/foundation-android-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.7.0/foundation-android-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-desktop/1.7.0/foundation-desktop-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-desktop/1.7.0/foundation-desktop-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-desktop/1.7.0/foundation-desktop-1.7.0.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-desktop",
        "version": "1.7.0"
      }
    }
  ]
}