{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.9.2/foundation-1.9.2.module",
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "14122761"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "foundation-android-1.9.2.aar",
          "size": 5154108,
          "sha512": "e692726834228a84e0a2b7fe112ac70d1c8469aaeb1b54a05bfbc5d3814c572a739ab2fd7b03387ca6a799b296d6c166767999780edcaac9d9cff801e7c2c2c2",
          "sha256": "2515efb3f5f1b2acdb9901aad85719346f3ebae8ce3d2e74ffec0244adc0e52a",
          "sha1": "bbf40fceaa8fcc293209aa00950947cde64c675d",
          "md5": "b84559862f9b9feff4d69c2133c79035"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "foundation-android-1.9.2.aar",
          "size": 5154108,
          "sha512": "e692726834228a84e0a2b7fe112ac70d1c8469aaeb1b54a05bfbc5d3814c572a739ab2fd7b03387ca6a799b296d6c166767999780edcaac9d9cff801e7c2c2c2",
          "sha256": "2515efb3f5f1b2acdb9901aad85719346f3ebae8ce3d2e74ffec0244adc0e52a",
          "sha1": "bbf40fceaa8fcc293209aa00950947cde64c675d",
          "md5": "b84559862f9b9feff4d69c2133c79035"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-1.9.2-samples-sources.jar",
          "url": "foundation-android-1.9.2-samples-sources.jar",
          "size": 87172,
          "sha512": "f6c6d56b83660a019e4df6edcacbd1503633990e8304262a14dfe6461f257aac525f8a5b3d2bfae498cab0410d5c1827a1fff79f74c4b0bcc6b470ee75f70549",
          "sha256": "9e80439b49c764cdcae2e74a1bba214a85fba0deaac672dd668a4eafcbfeda9f",
          "sha1": "927d417e21c50f15cd7f4a7c24433b7688d91f30",
          "md5": "e9cc244f25e0b12eb772bfbdc5bb9d14"
        },
        {
          "name": "foundation-android-1.9.2-sources.jar",
          "url": "foundation-android-1.9.2-sources.jar",
          "size": 1044819,
          "sha512": "8016c43a67ffad1413e606afc6e8605df8683098f44d4e84171b7ee21a84df50cdf67ba85f8a6ca3d268537267510c7bc257a73cb4f83f6f799fe445d0deec0b",
          "sha256": "b9461ba878f67fc83110ced72da43d97e871f65f8e59f892498dc7644d43a62c",
          "sha1": "540f4fb28a66e9b5d9e6f49127ea5f3931c2f95b",
          "md5": "3790b5bd43d5951106a9b602146e24ed"
        }
      ]
    }
  ]
}