{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-core/1.9.2/animation-core-1.9.2.module",
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "14122761"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core.aar",
          "url": "animation-core-android-1.9.2.aar",
          "size": 1341412,
          "sha512": "162e16e262689f8790055a991639a0b8f521c83c2a3a769ec8d17d4c0a5d4f79788e900e2c03ee6370a54b6e37d1235319b83e96596fbf63900407a181b9d6c8",
          "sha256": "7414c1525fdf8514a9570d4fbe90de26b8d3da74a5b25098c5fbd05fbedc0ede",
          "sha1": "830a5d4fac85504f63b25c40804297c21a5a3434",
          "md5": "aea4d24ced297cf9828ab278937b1526"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core.aar",
          "url": "animation-core-android-1.9.2.aar",
          "size": 1341412,
          "sha512": "162e16e262689f8790055a991639a0b8f521c83c2a3a769ec8d17d4c0a5d4f79788e900e2c03ee6370a54b6e37d1235319b83e96596fbf63900407a181b9d6c8",
          "sha256": "7414c1525fdf8514a9570d4fbe90de26b8d3da74a5b25098c5fbd05fbedc0ede",
          "sha1": "830a5d4fac85504f63b25c40804297c21a5a3434",
          "md5": "aea4d24ced297cf9828ab278937b1526"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-android-1.9.2-sources.jar",
          "url": "animation-core-android-1.9.2-sources.jar",
          "size": 115006,
          "sha512": "c29e27e6eceebfa6e73a66c6fc713af6b10709cccc5d9076ac90a7aa350e87009d52dfcb4106ee41988bca0942cf4c20b91e762be442bf0a3a7d2b8464557ff2",
          "sha256": "3954eebe794b5070d395b2ad8f7d5ca9ed54158e48480964a4788e876ebdeea6",
          "sha1": "2c4fedfaf1679df3feb7bfab4ecb815c84d9585d",
          "md5": "f18073c999e9038c3ff6d7caa7b0aa77"
        },
        {
          "name": "animation-core-1.9.2-samples-sources.jar",
          "url": "animation-core-android-1.9.2-samples-sources.jar",
          "size": 25951,
          "sha512": "c47d7caa2fa6ea92a57a886adecc37494bae8712706a45067ac3c1eed8dc599c9cfc258959cb4e73c3c00309f49a6867347f7f39f9a71fde8028324df6353ddf",
          "sha256": "cbd4b9814d7e2af91b3a22f554e75281beaf23c3f47016f98a79b1ac0f3cb6b2",
          "sha1": "ae139cc0ab318b5bb8cf986e43f25356bfc126c8",
          "md5": "a46005f614a432aa11f427df6ba5e618"
        }
      ]
    }
  ]
}