{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.7.0-multiplatform-sources.jar",
          "url": "ui-graphics-1.7.0-multiplatform-sources.jar",
          "size": 285418,
          "sha512": "2c67599fbc276b39e7b95fba36e516ab47bf4c89b71e83488ace6b7827744df69a7aa69e130de322f4df12a0a341ab37f2e684d5168f84c25ac2b4d0081b685a",
          "sha256": "32ba1dea0a2c39739c73ca32632177b2255e05ed426a23346a6501cf3879367e",
          "sha1": "9c4e7965e690736a0347452922eafce5e70c8f0d",
          "md5": "dd47bc28ccc9798c2776eed9d29f4ca1"
        },
        {
          "name": "ui-graphics-1.7.0-samples-sources.jar",
          "url": "ui-graphics-1.7.0-samples-sources.jar",
          "size": 9400,
          "sha512": "3a2ce8ff50ea9a05c19b77efd3d7c1875b86b218803b4ba476f6c61082db1f9668d3e48c9b71668b693fd566d806479fb040afb0fd24ecbe91774bb91e0032bd",
          "sha256": "7156bb25eb90ff1f285a49dc65c2318ab8f3ee0f23a9768cc2e06602112018df",
          "sha1": "ddfeff6f366b2b511196cec6c71f3c0003b795db",
          "md5": "f2b3ec09a7c4c2f2b21c71a04d70245e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-graphics-1.7.0-versionMetadata.json",
          "size": 85060,
          "sha512": "945d18778a58b6adcc69212d9615ca38ee0105af977b4c2b94dafd07d4875c1c551d81abff5ec0f99634f3f5200d82247ba7a4facdc3e2a75d319b8c70cce5b5",
          "sha256": "e353479bc67a65535ceac049f72b54c935d33a83dc893330a58df9fd7c2468be",
          "sha1": "91b63d678d1cb3a50a4488846bb2db619f51f5b6",
          "md5": "0b68253e1e4aa0af184959b615e4798b"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-graphics-metadata-1.7.0.jar",
          "url": "ui-graphics-1.7.0.jar",
          "size": 731,
          "sha512": "6abaa4d1a964a7c17fd04d3d8260474ecb77157b31efd4802696bbfbaf2b31cab83847aee710aef57024cc74b1ac5159de7cd5f98b911b17c112b99a271f592c",
          "sha256": "eebcaad22243f49e712aae8ea011d72fb5caedd250e27e6cecd6a5b20fb61872",
          "sha1": "a63730bfb506f6b85f993e783c7feedd8b02a1c0",
          "md5": "2fd6e9c0f5248b4904051bee3f0327ad"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-graphics-kotlin-1.7.0-sources.jar",
          "url": "ui-graphics-1.7.0-sources.jar",
          "size": 189873,
          "sha512": "46554f09aa7d00e9274a81b68e1593cb55c6e08b451c8ba3a0b8eb72a9594da65577ec590afae0228218a9da02ec7b00fd76f21e4c5539ad56cad3bd428a05b0",
          "sha256": "aaf4ddae4d66f6c19fa9d2d3925e54172635c58f1c0dfa0a4a6dc053701261ef",
          "sha1": "2bd53d0fa3d1bc8ecc06b953d684b635ee66b03d",
          "md5": "b2b788bdd30690e3e5db69ff3a6f99a0"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-graphics-android/1.7.0/ui-graphics-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-graphics-android/1.7.0/ui-graphics-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-graphics-android/1.7.0/ui-graphics-android-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-graphics-desktop/1.7.0/ui-graphics-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-graphics-desktop/1.7.0/ui-graphics-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-graphics-desktop/1.7.0/ui-graphics-desktop-1.7.0.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-desktop",
        "version": "1.7.0"
      }
    }
  ]
}