{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "material-ripple-1.7.0-multiplatform-sources.jar",
          "url": "material-ripple-1.7.0-multiplatform-sources.jar",
          "size": 28431,
          "sha512": "80505077d1822efadbd69b5ebc7877777a6109285ebb6fe817f71ac3e10e15495992b48e7d546f552292b1d1464b3e0adad932e12a3026d49f39a4ce57d58098",
          "sha256": "22c0104ca3f3648ae69732f056a223fd27a99e40b5c05f3600dc667c89dd27a5",
          "sha1": "fecf0d62bbdcb8e5259f12706472290c942b5404",
          "md5": "6a919a5174e9ca2f2a38d03272c3644f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material-ripple-1.7.0-versionMetadata.json",
          "size": 1708,
          "sha512": "d602d1ed0bc72bcf23f8845069a63b0a003295079d19cc09d0434908b0c73f0a36884b42b78c327ffde567a400c59095440554d39b99a3ad9e73ac78df70f9ce",
          "sha256": "c954aeabab5f274b39081150daea31c4022aad12be8dbc22beb0fdda9a41f796",
          "sha1": "cdfecb6af18415a50fbd1cc38fa54c0cc8544b8b",
          "md5": "1a9a68848705da85f2023977b4222574"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-metadata-1.7.0.jar",
          "url": "material-ripple-1.7.0.jar",
          "size": 738,
          "sha512": "b88adab5159fc7ae006e7b5b9662f5edecd6e92e22954f6ae2d0838c5bece7e7a57bcbb07b3fba63493b74038450c440de9196aab93b893338600fb9bb953c3b",
          "sha256": "3018ecf7ef0302f1c2492e4c627ae36b763167779b4595fa89331553f5b0c51a",
          "sha1": "ea4753f9abbd0c3933fe6e0a63e312bf5ee4ce53",
          "md5": "ab7a0bc48ccce06f8cfe54c6eda193ae"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material-ripple-kotlin-1.7.0-sources.jar",
          "url": "material-ripple-1.7.0-sources.jar",
          "size": 13695,
          "sha512": "19f4740ce9031717c0fe5809f09faef1bbfd98fc7da3da0db4635de6d81f7b84e6fec3888c331b8f2cd8edf664b4781c6cf2e2b4335752d7c15b56ca82c5ea63",
          "sha256": "88957e361d1f516ee25f8d8a824ee980c5fa9da3ee42f8278733ba198952c000",
          "sha1": "7bbd4ab08e6dd197616650ad06f49a7453696c68",
          "md5": "2c61057771ae88281599b3ff12c39784"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-ripple-android/1.7.0/material-ripple-android-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-ripple-android/1.7.0/material-ripple-android-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-ripple-android/1.7.0/material-ripple-android-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-desktop/1.7.0/material-ripple-desktop-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-desktop/1.7.0/material-ripple-desktop-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-desktop/1.7.0/material-ripple-desktop-1.7.0.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-desktop",
        "version": "1.7.0"
      }
    }
  ]
}